added subscription environment variable for SYNC-PERIOD-MIN
RHEcosystemAppEng/dbaas-operator pull request #105
Opened 2022-01-28 17:43 UTC by redhatHameed

The operator does not allow users to change environment variables. All changes get reverted. the possible solution is to add into subscription config: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/subscription-config.md#subscription-config

## Description

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2022-01-31 16:05 UTC, tchughesiv commented on api/v1alpha1/dbaasplatform_types.go
> +	SyncPeriod string `json:"syncPeriod,omitempty"`
would it be a good idea to make this an integer instead? then convert to string in code?

2022-01-31 16:26 UTC, redhatHameed commented on api/v1alpha1/dbaasplatform_types.go
> +	SyncPeriod string `json:"syncPeriod,omitempty"`
make sense, added validation as well. updated

2022-01-31 16:32 UTC, tchughesiv commented on config/crd/bases/dbaas.redhat.com_dbaasplatforms.yaml
> +                maximum: 180
any reason 180 is the max here? just curious

2022-01-31 16:51 UTC, tchughesiv requested changes
can we add a couple unit tests that verify no ENV is set when `cr.Spec.SyncPeriod` is empty? and another that verifies one IS set? also, what happens if an empty `SYNC-PERIOD-MIN` var is set? does that mean no refresh?

2022-01-31 17:01 UTC, tchughesiv requested changes

2022-01-31 17:01 UTC, tchughesiv commented on api/v1alpha1/dbaasplatform_types.go
> +	SyncPeriod int `json:"syncPeriod,omitempty"`
can we add a description here?

2022-01-31 19:24 UTC, jianrongzhang89 commented on config/crd/bases/dbaas.redhat.com_dbaasplatforms.yaml
> +                maximum: 180
@redhatHameed you can set default: 180 instead of maximum.

2022-01-31 20:01 UTC, redhatHameed commented on config/crd/bases/dbaas.redhat.com_dbaasplatforms.yaml
> +                maximum: 180
@jianrongzhang89 Thanks default already set by provider operator.

@tchughesiv added 24h max value

2022-01-31 20:01 UTC, redhatHameed commented on api/v1alpha1/dbaasplatform_types.go
> +	SyncPeriod int `json:"syncPeriod,omitempty"`
added

2022-01-31 20:02 UTC, redhatHameed commented
> can we add a couple unit tests that verify no ENV is set when `cr.Spec.SyncPeriod` is empty? and another that verifies one IS set? also, what happens if an empty `SYNC-PERIOD-MIN` var is set? does that mean no refresh?

added unit test.

added if check if empty/nil cr.Spec.SyncPeriod don't set environment variable

2022-01-31 20:15 UTC, tchughesiv approved these changes
Lgtm

2022-01-31 20:17 UTC, tchughesiv requested changes

2022-01-31 20:17 UTC, tchughesiv commented on controllers/dbaasplatform_controller_test.go
> +		AfterEach(assertResourceDeletion(cr))
Sorry, Can we check the resulting subscription here? See if env var is set or not

2022-02-01 19:11 UTC, redhatHameed commented on controllers/dbaasplatform_controller_test.go
> +		AfterEach(assertResourceDeletion(cr))
This required a complete platform installations unit test as currently not added. I have given try but there are some other issues faced, also we have dependencies on platform installation on openshift real environment and installation never completed see logs:
https://gist.github.com/redhatHameed/2ca684b6488b77193ab77b0591c933fb

2022-02-01 19:18 UTC, tchughesiv approved these changes
lgtm

2022-02-01 19:18 UTC, merged