DBAAS-257: add docs teams' RHODA quick-starts on installation
RHEcosystemAppEng/dbaas-operator pull request #112
Opened 2022-02-07 22:42 UTC by jeremyary

## Description

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2022-02-07 22:51 UTC, jeremyary commented on controllers/reconcilers/quickstart_installation/quickstart_installation_reconciler.go
> +var connectionQuickStart []byte
to point out the new voodoo here, these lines grab YAML files in the same directory & shove them into byte slices, simple as that. I don't touch them again until they `yaml.unmarshal` @L58

2022-02-08 13:43 UTC, redhatHameed commented on controllers/dbaasplatform_controller.go
> +		dbaasv1alpha1.DBaaSQuickStartInstallation,
can we change the order of quick start installation, adding in the last? WDYT?

2022-02-08 14:18 UTC, redhatHameed commented
> Adds quickstart content provided by our docs teams to the cluster by means of a new installation phase. The content comes from here. The result is that if you access Quick Starts, either by the link from our OLM operator card or via the "?" help menu in the top-right corner, you will be able to access these new Quick Start cards:
> 
> ![2022-02-07_16-17](https://user-images.githubusercontent.com/1012188/152884799-9190ba92-40a8-4914-a091-1e539327c354.png)
> 
> ![2022-02-07_16-45](https://user-images.githubusercontent.com/1012188/152884972-5b0d4fe0-6e57-4488-877a-5f3ef38f8b91.png)
> 
> ![2022-02-07_16-46](https://user-images.githubusercontent.com/1012188/152885049-fe0384dc-3dd8-4fc0-a7eb-62d7f5707bbb.png)

are we planning to add creating the trial instance in a quick start doc?

2022-02-08 14:25 UTC, jeremyary commented
We will have another card, but it's up to Docs as to what cards we get or how they're combined. We'll just receive YAML and put into directory. The provisioning card will be ready once we can get docs team solid UI and e2e experience so they can finish it up.

2022-02-08 14:28 UTC, jeremyary commented on controllers/dbaasplatform_controller.go
> +		dbaasv1alpha1.DBaaSQuickStartInstallation,
sure, updated

2022-02-08 14:30 UTC, redhatHameed approved these changes
LGTM

2022-02-08 14:33 UTC, tchughesiv requested changes

2022-02-08 14:43 UTC, jeremyary commented on controllers/reconcilers/quickstart_installation/quickstart_installation_reconciler.go
> +	err := yaml.Unmarshal(qsBytes, quickStartFromFile)
yeah that's fair, I wasn't sure how much resource creation was worth testing but I adding cvg for embed/marshalling makes sense. Update shortly.

2022-02-08 20:57 UTC, jeremyary commented on controllers/reconcilers/quickstart_installation/quickstart_installation_reconciler.go
> +	err := yaml.Unmarshal(qsBytes, quickStartFromFile)
tests added to unmarshal each ConsoleQuickStart YAML and make several assertions about their content.

2022-02-08 21:16 UTC, tchughesiv approved these changes
lgtm

2022-02-08 21:17 UTC, merged