Deleted old QSG files, add 2 new OSG files, updated go reconciler
RHEcosystemAppEng/dbaas-operator pull request #115
Opened 2022-02-11 21:35 UTC by ritz303

## Description
Consolidated multiple Quick Start Guides (QSG) into two QSGs, one for each workflow (Admin, Dev).
These updated QSGs cover the doc request being tracked under this Jira epic - https://issues.redhat.com/browse/DBAAS-206

## Verification Steps
Add the QSGs to a shared OCP 4.9 cluster in the QuickLab environment.
Direct message me if you want access to this QuickLab environment to review what these QSGs look like.

## Type of change
- [Added] New doc updates (non-breaking change which adds functionality)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2022-02-12 00:23 UTC, jeremyary requested changes

2022-02-14 00:25 UTC, ritz303 commented on controllers/reconcilers/quickstart_installation/quickstart_installation_reconciler.go
> +// 2.11.22 - gunnage : go:embed getting-started-with-openshift-database-access-for-administrators-quick-start.yaml
Good to know.  I didn't know that had a special meaning, I thought it was just a comment line.  Thanks for taking a look!

2022-02-14 14:31 UTC, jeremyary requested changes
https://github.com/ritz303/dbaas-operator/pull/1

Hey Aron, I missed a formatting recommendation in my previous review. This ^ is a PR that should fix that in your branch.

2022-02-14 15:16 UTC, ritz303 commented
@jeremyary : Thanks for taking a look!  I've merged your PR into my branch.

2022-02-14 15:27 UTC, merged

2022-02-14 15:28 UTC, jeremyary commented
@ritz303 all green, merged up. Thanks for the contribution!