Add webhook for dbaastenant to only allow one tenant object per inventory namespace
RHEcosystemAppEng/dbaas-operator pull request #132
Opened 2022-03-08 15:38 UTC by xieshenzh

## Description

We should only allow one tenant object per inventory namespace. The validating webhook should check if an existing tenant exists with the same spec.inventoryNamespace setting. 

https://issues.redhat.com/browse/DBAAS-379

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2022-03-08 15:46 UTC, jeremyary commented
Thanks Xieshen! Holding for when we open up main for Beta soon and will circle back to review

2022-03-08 15:49 UTC, tchughesiv approved these changes
lgtm

2022-03-08 15:52 UTC, redhatHameed submitted a review, later dismissed
LGTM

2022-03-21 13:41 UTC, tchughesiv requested changes
lgtm, but please rebase and resolve conflicts

2022-03-21 14:53 UTC, tchughesiv approved these changes

2022-03-21 14:53 UTC, merged