DBAAS-364: Add a new Instance Phase `Error`, `Failed` and `Unknown`
RHEcosystemAppEng/dbaas-operator pull request #133
Opened 2022-03-08 15:42 UTC by xieshenzh

## Description

Add a new Instance Phase `Error`, `Failed` and `Unknown`.  
Use them to indicate cluster terminal states with issues, for example CockroachDB Cloud`CreationFailed`.
Also add kubebuilder marker to the `Phase` field to enforce restriction on the allowed values.

https://issues.redhat.com/browse/DBAAS-364

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2022-03-08 15:46 UTC, jeremyary commented
Thanks Xieshen! Holding for when we open up main for Beta soon and will circle back to review

2022-03-21 15:38 UTC, jianrongzhang89 commented on bundle/manifests/dbaas.redhat.com_dbaasinstances.yaml
> +                - Error
@xieshenzh if an error is temporary and can be automatically recovered in a future reconciliation, I think we should consider it as part of normal processing, because otherwise, the user may see such an "error" state very often.

2022-03-21 15:41 UTC, xieshenzh commented on bundle/manifests/dbaas.redhat.com_dbaasinstances.yaml
> +                - Error
The recovery may require user involvement.

2022-06-09 13:46 UTC, redhatHameed commented
I observed that phase value not copied into `DBaaSInstance` CR when the CR get deleted. do we need to considered this thing here ? also with PR, we might need to fix phase status accordingly into provider operators.
cc @jeremyary

2022-06-29 13:13 UTC, jianrongzhang89 commented on bundle/manifests/dbaas.redhat.com_dbaasinstances.yaml
> +                - Error
OK

2022-06-29 13:14 UTC, jianrongzhang89 commented
LGTM

2022-06-29 15:03 UTC, redhatHameed commented
we may need to revisit the providers code as far as I know about crunchy, as these are only accepted values for phase.

2022-06-29 15:11 UTC, jeremyary commented
> we may need to revisit the providers code as far as I know about crunchy, as these are only accepted values for phase.

thanks AH, that's what I was worried about. We don't want to push something at this stage that's going to cause provider rework and make us go back to mongo and cockroach again for this release to get more images.

2022-06-29 15:16 UTC, jianrongzhang89 commented
> 

I think each provider operator only needs to implement a subset of these phase values. If some values are not applicable they just get ignored by the provider operator.

2022-06-29 15:20 UTC, redhatHameed commented
> > 
> 
> I think each provider operator only needs to implement a subset of these phase values. If some values are not applicable they just get ignored by the provider operator.

like crunchy set unknown phase as empty value, so it will cause error while setting phase as that will not be accepted enum value

2022-06-29 15:22 UTC, xieshenzh commented
> > we may need to revisit the providers code as far as I know about crunchy, as these are only accepted values for phase.
> 
> thanks AH, that's what I was worried about. We don't want to push something at this stage that's going to cause provider rework and make us go back to mongo and cockroach again for this release to get more images.

This change is actually requested by cockroach. They were expecting the change for the next release. There is a pull request for cockroach too: https://github.com/cockroachdb/ccapi-k8s-operator/pull/6

Anyways, I'll start using the values for the providers. It is not a big problem if dbaas operator doesn't accept some of the values.

2022-07-20 20:41 UTC, jianrongzhang89 requested changes
@xieshenzh I took a further look at this PR, and I think we'd better distinguish the phase (what the provisioning process is doing) from the status (whether there is an error in that phase), and this is what we have so far.

So instead of introducing the new phases (error, failed, unknown), I'd suggest we keep the existing list of phase values (pending, creating etc).  Errors can happen in any phase (creating, upgrading etc), and such separation provides users a better view of the current provisioning status: which phase it has been doing and what error it has happened.

If there are errors/failures happen, we keep the existing phase value and at the same time, we set the condition status to false along with the error reason and message. In this way, no changes in the UX, or Mongo/Crunchy and Crdnb operators are needed.  What do you think? - we can set up a meeting to discuss if needed.

Adding other team members @jeremyary @redhatHameed @tchughesiv @myeung18 @yzhao583 @olavtar for their opinions.

2022-07-21 21:00 UTC, xieshenzh commented
> > > 
> > 
> > 
> > I think each provider operator only needs to implement a subset of these phase values. If some values are not applicable they just get ignored by the provider operator.
> 
> like crunchy set unknown phase as empty value, so it will cause error while setting phase as that will not be accepted enum value

`Unknown` will be the default value if it is not set. The point of using `Unknown` as the default value is to avoid empty value.

2022-07-22 13:42 UTC, jianrongzhang89 commented
> > > > 
> > > 
> > > 
> > > I think each provider operator only needs to implement a subset of these phase values. If some values are not applicable they just get ignored by the provider operator.
> > 
> > 
> > like crunchy set unknown phase as empty value, so it will cause error while setting phase as that will not be accepted enum value
> 
> `Unknown` will be the default value if it is not set. The point of using `Unknown` as the default value is to avoid empty value.

We also have a pending phase defined which basically means that the provisioning processing has not started. Can we use it as the default phase?

2022-07-22 13:46 UTC, jianrongzhang89 commented
> > @xieshenzh I took a further look at this PR, and I think we'd better distinguish the phase (what the provisioning process is doing) from the status (whether there is an error in that phase), and this is what we have so far.
> > So instead of introducing the new phases (error, failed, unknown), I'd suggest we keep the existing list of phase values (pending, creating etc). Errors can happen in any phase (creating, upgrading etc), and such separation provides users a better view of the current provisioning status: which phase it has been doing and what error it has happened.
> > If there are errors/failures happen, we keep the existing phase value and at the same time, we set the condition status to false along with the error reason and message. In this way, no changes in the UX, or Mongo/Crunchy and Crdnb operators are needed. What do you think? - we can set up a meeting to discuss if needed.
> > Adding other team members @jeremyary @redhatHameed @tchughesiv @myeung18 @yzhao583 @olavtar for their opinions.
> 
> I think the phase should represent the current state of the DB instances, not what has been doing or what happened. It is true that errors could happen in any of the existing phases, but for some providers a DB instance could transit to an error state from the ready state. In this case, if the error is only in the status conditions, the phase of the instance will be ready when there are errors in the status. It looks confusing. And errors in status cannot represent the final state of DB instances. Imagine a DB instance with phase ready but it is actually terminated, and in the status provisioning is not ready. It is also confusing. I don't think the existing phase values are generic enough to cover all the scenarios that I encountered for cockroach or RDS. Since you don't agree that we need to impose the rule for all providers, I can close the PR and let different providers have different definitions of phase.

I think the phase should represent the state of the provisioning process and should be separated from the actual state of the DB instance. Lets discuss this issue in the next team meeting and see how we should handle it.

2022-07-22 15:19 UTC, xieshenzh commented
> We also have a pending phase defined which basically means that the provisioning processing has not started. Can we use it as the default phase?

We could use `Pending` instead of `Unknown`. But crunchy is not using `Pending` as the default phase: https://github.com/CrunchyData/crunchy-bridge-operator/blob/8ca94f65f62d1098ed3acb21e0e268d5323ba380/controllers/dbaas.redhat.com/crunchybridgeinstance_controller.go#L134-L149

So whether using `Pending` or `Unknown`, crunchy will need to be updated.

2022-07-27 18:07 UTC, xieshenzh commented
> I think the phase should represent the state of the provisioning process and should be separated from the actual state of the DB instance. Lets discuss this issue in the next team meeting and see how we should handle it.

1. In the documentation of Pod, the phase of a pod means [the state of the pod in its lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase:~:text=The%20phase%20of%20a%20Pod%20is%20a%20simple%2C%20high%2Dlevel%20summary%20of%20where%20the%20Pod%20is%20in%20its%20lifecycle.%20The%20phase%20is%20not%20intended%20to%20be%20a%20comprehensive%20rollup%20of%20observations%20of%20container%20or%20Pod%20state%2C%20nor%20is%20it%20intended%20to%20be%20a%20comprehensive%20state%20machine.).  So when a user sees the `Phase` in the status of an Instance, the phase will be treated as the state of the db instance in its lifecycle intuitively. While a pod doesn't have a state of error, a db instance could have errors which could be irrelevant to its provisioning process. So if we need a field to represent the state of the provisioning process, it is better to name it `ProvisionPhase`.

2.  In our [doc](https://github.com/RHEcosystemAppEng/dbaas-operator/blob/c37b04d154b544578eac518d793a4cfd98cb9bd5/api/v1alpha1/dbaasprovider.go#L242-L244) for `Phase`, value `Ready` means cluster provisioning complete, so `Ready` should be the final state of the provisioning process. But we also have value `Updating`, `Deleting` and `Deleted`, apparently they are not part of the provisioning process, they could happen after the `Ready` phase, they are used to represent the state of the db instance. If we want to use `Phase` to represent the provisioning process, we need to redefine the acceptable values and modify all the provider operators.

3.  In the implementation of mongo atlas provider operator, the [value of cluster state](https://github.com/RHEcosystemAppEng/mongodb-atlas-kubernetes/blob/16dc5c33111ba2e4c19377557c63b177656c4216/pkg/controller/atlasinventory/inventory.go#L79) is used as the `Phase` of the instance. In my opinion, it means the `Phase` is used to represent the cluster state instead of provisioning state in this case as well. And mongo already uses [`Failed` as a value for `Phase`](https://github.com/RHEcosystemAppEng/mongodb-atlas-kubernetes/blob/16dc5c33111ba2e4c19377557c63b177656c4216/pkg/controller/atlasinstance/atlasinstance_controller.go#L86),  which will only be a valid value in our doc if this PR is merged.

If we don't care users see different values of `Phase` from different providers, then let's not add restrictions on this field and close this PR. However, if the restrictions are supposed to be added in the future, it will be much more difficult to do it later.

2022-07-28 17:37 UTC, jianrongzhang89 commented
> > I think the phase should represent the state of the provisioning process and should be separated from the actual state of the DB instance. Lets discuss this issue in the next team meeting and see how we should handle it.
> 
> 1. In the documentation of Pod, the phase of a pod means [the state of the pod in its lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase:~:text=The%20phase%20of%20a%20Pod%20is%20a%20simple%2C%20high%2Dlevel%20summary%20of%20where%20the%20Pod%20is%20in%20its%20lifecycle.%20The%20phase%20is%20not%20intended%20to%20be%20a%20comprehensive%20rollup%20of%20observations%20of%20container%20or%20Pod%20state%2C%20nor%20is%20it%20intended%20to%20be%20a%20comprehensive%20state%20machine.).  So when a user sees the `Phase` in the status of an Instance, the phase will be treated as the state of the db instance in its lifecycle intuitively. While a pod doesn't have a state of error, a db instance could have errors which could be irrelevant to its provisioning process. So if we need a field to represent the state of the provisioning process, it is better to name it `ProvisionPhase`.
> 2. In our [doc](https://github.com/RHEcosystemAppEng/dbaas-operator/blob/c37b04d154b544578eac518d793a4cfd98cb9bd5/api/v1alpha1/dbaasprovider.go#L242-L244) for `Phase`, value `Ready` means cluster provisioning complete, so `Ready` should be the final state of the provisioning process. But we also have value `Updating`, `Deleting` and `Deleted`, apparently they are not part of the provisioning process, they could happen after the `Ready` phase, they are used to represent the state of the db instance. If we want to use `Phase` to represent the provisioning process, we need to redefine the acceptable values and modify all the provider operators.
> 3. In the implementation of mongo atlas provider operator, the [value of cluster state](https://github.com/RHEcosystemAppEng/mongodb-atlas-kubernetes/blob/16dc5c33111ba2e4c19377557c63b177656c4216/pkg/controller/atlasinventory/inventory.go#L79) is used as the `Phase` of the instance. In my opinion, it means the `Phase` is used to represent the cluster state instead of provisioning state in this case as well. And mongo already uses [`Failed` as a value for `Phase`](https://github.com/RHEcosystemAppEng/mongodb-atlas-kubernetes/blob/16dc5c33111ba2e4c19377557c63b177656c4216/pkg/controller/atlasinstance/atlasinstance_controller.go#L86),  which will only be a valid value in our doc if this PR is merged.
> 
> If we don't care users see different values of `Phase` from different providers, then let's not add restrictions on this field and close this PR. However, if the restrictions are supposed to be added in the future, it will be much more difficult to do it later.

Thank you for your clarification. Yes we might use phase later on if we want to support instance update and deletion, so you are right, "phase" is not strictly for provisioning (creation). 

I have one more question: why do we need "error" phase? If this is a temporary error that can be recovered by the controller automatically, the status should not be updated and we simply requeue the request for reconciliation. (as we do now for cases such as an object retrieval is not available temporaily).

2022-07-28 17:58 UTC, xieshenzh commented
> I have one more question: why do we need an "error" phase? If this is a temporary error that can be recovered by the controller automatically, the status should not be updated and we can simply log the errors and requeue the request for reconciliation. (as we do now for cases such as an object retrieval is not available temporarily).

If the error happens on the controller side, in most cases, the phase would be `Updating`, `Creating` or `Deleting`.

`Error` phase means something is wrong on the provider side and the controller sets the phase to `Error` based on the db instance state returned from the provider. For example, there are [more than 20 different states](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/accessing-monitoring.html#Overview.DBInstance.Status) for RDS db instances, some of them could be categorized as `Error`, because in these cases user could fix the issues on AWS, but there is nothing the controller can do to change the state of the db instance.

2022-07-28 18:26 UTC, jianrongzhang89 commented
> 

Thanks you @xieshenzh . Could you update the ADR https://docs.google.com/document/d/1Ab2IzFwYndpy1Yw0YXSRfk54onUiqQU8eEQmAez1kGo/edit?usp=sharing with some detail on these values?

2022-07-28 18:27 UTC, jianrongzhang89 submitted a review, later dismissed
This PR looks good to me.

2022-07-28 18:35 UTC, xieshenzh commented
> > 
> 
> Thanks you @xieshenzh . Could you update the ADR https://docs.google.com/document/d/1Ab2IzFwYndpy1Yw0YXSRfk54onUiqQU8eEQmAez1kGo/edit?usp=sharing with some detail on these values?

Sure, updated the instance phase section in the doc.

2022-08-25 14:06 UTC, jeremyary commented
@tchughesiv @redhatHameed PTAL when you have a chance, looks to be updated as of yesterday, thanks. @xieshenzh if any other work is blocked/dependent/linked to this, please be sure and call that out from this PR, thanks!

2022-08-25 14:53 UTC, xieshenzh commented
> @tchughesiv @redhatHameed PTAL when you have a chance, looks to be updated as of yesterday, thanks. @xieshenzh if any other work is blocked/dependent/linked to this, please be sure and call that out from this PR, thanks!

Please also review these PRs:
https://github.com/RHEcosystemAppEng/mongodb-atlas-kubernetes/pull/55
https://github.com/CrunchyData/crunchy-bridge-operator/pull/54
These should be merged with this PR.

Once this PR is merged, I'll update the provider operators to use the Phase constants introduced in this PR.

2022-08-29 19:17 UTC, jeremyary approved these changes

2022-08-29 19:17 UTC, merged