DbaaS-58: Refactor controllers
RHEcosystemAppEng/dbaas-operator pull request #14
Opened 2021-06-18 21:25 UTC by xieshenzh

## Description

Refactor DBaaS Operator controllers based ADR.

Jira: https://issues.redhat.com/browse/DBAAS-58

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2021-06-20 22:23 UTC, bmozaffa requested changes
Thanks for all the progress, Xieshen! I didn't go very deep in my review, but just made a couple of non-functional comments that caught my eyes

2021-06-20 22:23 UTC, bmozaffa commented on controllers/providers.go
> +	reconciler DBaaSReconciler
It would be good to remove the circular dependency, where this struct has a reference to the controllers and they in turn have a reference to this one. Why not have this struct be created from main.go with client/scheme in it and then held by the two controllers and used for all k8s operations? They would then not directly hold client/scheme, and the relationship would be one-way from the controllers to this struct.

2021-06-20 22:23 UTC, bmozaffa commented on controllers/providers.go
> +type DBaaSProvider struct {
To go with my other comment, this can then be called the DBaaSReconciler to avoid confusion between controllers.DBaaSProvider and v1alpha1.DBaaSProvider

2021-06-20 22:23 UTC, bmozaffa commented on controllers/providers.go
> +type DBaaSProvider struct {
If so, maybe also rename the file?

2021-06-24 17:37 UTC, jeremyary commented
Looking good to me, but I definitely think we should walk through this with at least manually creating a provider configMap and see how it goes. Xieshen, are you wanting to add more tests to this PR or you ready to get this one merged up?

2021-06-24 18:21 UTC, xieshenzh commented
> Looking good to me, but I definitely think we ('we' being me or another eng) should walk through this by manually creating a provider configMap and see how it goes. Xieshen, are you wanting to add more tests to this PR or you ready to get this one merged up?

Sure, I can work on the unit tests while you try to integrate with provider operator.
I manually tested with a config map like below, it worked.
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: mongodb-atlas
  labels:
    related-to: dbaas-operator
    type: dbaas-provider-registration
data:
  connection_kind: MongoDBAtlasConnection
  credentials_fields: |
    field1.key: field1
    field1.display_name: Field11
    field1.type: string
    field1.required: true
    field2.key: field2
    field2.display_name: Field21
    field2.type: maskedstring
    field2.required: true
  inventory_kind: MongoDBAtlasInventory
  provider: MongoDBAtlas
```

2021-06-25 15:10 UTC, redhatHameed commented
> > Looking good to me, but I definitely think we ('we' being me or another eng) should walk through this by manually creating a provider configMap and see how it goes. Xieshen, are you wanting to add more tests to this PR or you ready to get this one merged up?
> 
> Sure, I can work on the unit tests while you try to integrate with provider operator.
> I manually tested with a config map like below, it worked.
> 
> ```
> kind: ConfigMap
> apiVersion: v1
> metadata:
>   name: mongodb-atlas
>   labels:
>     related-to: dbaas-operator
>     type: dbaas-provider-registration
> data:
>   connection_kind: MongoDBAtlasConnection
>   credentials_fields: |
>     field1.key: field1
>     field1.display_name: Field11
>     field1.type: string
>     field1.required: true
>     field2.key: field2
>     field2.display_name: Field21
>     field2.type: maskedstring
>     field2.required: true
>   inventory_kind: MongoDBAtlasInventory
>   provider: MongoDBAtlas
> ```
 can we test with with the actual provider operator,  I have created the config map  for crunchy bridge operator inside namespace `dbaas-operator` and crunchybridge operator deplpoyed inside namespace''

2021-06-25 17:21 UTC, redhatHameed commented
> > > Looking good to me, but I definitely think we ('we' being me or another eng) should walk through this by manually creating a provider configMap and see how it goes. Xieshen, are you wanting to add more tests to this PR or you ready to get this one merged up?
> > 
> > 
> > Sure, I can work on the unit tests while you try to integrate with provider operator.
> > I manually tested with a config map like below, it worked.
> > ```
> > kind: ConfigMap
> > apiVersion: v1
> > metadata:
> >   name: mongodb-atlas
> >   labels:
> >     related-to: dbaas-operator
> >     type: dbaas-provider-registration
> > data:
> >   connection_kind: MongoDBAtlasConnection
> >   credentials_fields: |
> >     field1.key: field1
> >     field1.display_name: Field11
> >     field1.type: string
> >     field1.required: true
> >     field2.key: field2
> >     field2.display_name: Field21
> >     field2.type: maskedstring
> >     field2.required: true
> >   inventory_kind: MongoDBAtlasInventory
> >   provider: MongoDBAtlas
> > ```
> 
> can we test with the actual provider operator, I have created the config map for crunchy bridge operator inside namespace `dbaas-operator` and crunchy bridge operator deployed inside namespace-> crunchy-bridge-operator-system

Btw I have installed DBaaS operator using your code , create inventory and connection CR, look good to me seeing below logs ``` -

2021-06-25T17:11:52.296Z	INFO	controller-runtime.manager.controller.dbaasconnection	Found DBaaS Provider	{"reconciler group": "dbaas.redhat.com", "reconciler kind": "DBaaSConnection", "name": "dbaasconnection-sample", "namespace": "dbaas-operator", "DBaaS Connection": "dbaas-operator/dbaasconnection-sample", "DBaaS Provider": {"name":"Crunchy Bridge managed PostgreSQL"}}

2021-06-25T17:11:52.305Z	INFO	controller-runtime.manager.controller.dbaasconnection	Provider Connection spec updated	{"reconciler group": "dbaas.redhat.com", "reconciler kind": "DBaaSConnection", "name": "dbaasconnection-sample", "namespace": "dbaas-operator", "DBaaS Connection": "dbaas-operator/dbaasconnection-sample"}
2021-06-25T17:11:52.537Z	INFO	controller-runtime.manager.controller.dbaasconnection	Found DBaaS Provider	{"reconciler group": "dbaas.redhat.com", "reconciler kind": "DBaaSConnection", "name": "dbaasconnection-sample", "namespace": "dbaas-operator", "DBaaS Connection": "dbaas-operator/dbaasconnection-sample", "DBaaS Provider": {"name":"Crunchy Bridge managed PostgreSQL"}}
2021-06-25T17:11:52.560Z	INFO	controller-runtime.manager.controller.dbaasconnection	DBaaS Connection status updated	{"reconciler group": "dbaas.redhat.com", "reconciler kind": "DBaaSConnection", "name": "dbaasconnection-sample", "namespace": "dbaas-operator", "DBaaS Connection": "dbaas-operator/dbaasconnection-sample"}

2021-06-25T17:11:52.567Z	INFO	controller-runtime.manager.controller.dbaasconnection	Found DBaaS Provider	{"reconciler group": "dbaas.redhat.com", "reconciler kind": "DBaaSConnection", "name": "dbaasconnection-sample", "namespace": "dbaas-operator", "DBaaS Connection": "dbaas-operator/dbaasconnection-sample", "DBaaS Provider": {"name":"Crunchy Bridge managed PostgreSQL"}}

2021-06-25T17:11:52.577Z	INFO	controller-runtime.manager.controller.dbaasconnection	DBaaS Connection status updated	{"reconciler group": "dbaas.redhat.com", "reconciler kind": "DBaaSConnection", "name": "dbaasconnection-sample", "namespace": "dbaas-operator", "DBaaS Connection": "dbaas-operator/dbaasconnection-sample"}

2021-06-25T17:11:52.583Z	INFO	controller-runtime.manager.controller.dbaasconnection	Provider Connection spec updated	{"reconciler group": "dbaas.redhat.com", "reconciler kind": "DBaaSConnection", "name": "dbaasconnection-sample", "namespace": "dbaas-operator", "DBaaS Connection": "dbaas-operator/dbaasconnection-sample"}```

2021-06-30 13:48 UTC, jeremyary approved these changes
@redhatHameed thanks for trying it out with provider CM. @xieshenzh if you're ready for this one to merge, LMK and we can carry unit testing into new PR if you'd prefer, your call.

2021-06-30 15:23 UTC, xieshenzh commented
@jeremyary I made some changes for watching configmap to re-deploy the operator, and then added unit tests. I think I should create another PR for these changes, otherwise there will be too much to review in this PR.

@redhatHameed and @jianrongzhang89 are doing further testing on Status subresource update of the provider Connection. We can merge this PR after that.

2021-06-30 16:31 UTC, redhatHameed approved these changes

2021-07-02 15:11 UTC, merged