DBaaS-95&99: Update dbaas-operator to be cluster-scoped, hide DBaaSConnection from OLM
RHEcosystemAppEng/dbaas-operator pull request #18
Opened 2021-07-10 04:17 UTC by xieshenzh

## Description

1. hide DBaaSConnection from OLM: https://issues.redhat.com/browse/DBAAS-99
2. update dbaas-operator to be cluster-scoped: https://issues.redhat.com/browse/DBAAS-95

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2021-07-10 11:41 UTC, tchughesiv requested changes

2021-07-10 11:41 UTC, tchughesiv commented on PROJECT
> +    namespaced: false
the CRDs themselves should stay namespace scoped. CRD scoping is completely separate from Operator scoping. This should remain true.

2021-07-10 11:41 UTC, tchughesiv commented on PROJECT
> +    namespaced: false
the CRDs themselves should stay namespace scoped. CRD scoping is completely separate from Operator scoping. This should remain true.

2021-07-10 11:43 UTC, tchughesiv commented on PROJECT
> +    namespaced: false
this is important so that developers can set connections within their namespaces.

2021-07-10 11:43 UTC, tchughesiv commented on PROJECT
> +    namespaced: false
this is important so that tetant service admins can set inventory specific to a given tenant.

2021-07-13 12:15 UTC, jeremyary approved these changes

2021-07-13 12:15 UTC, merged