added environment variables for dev observatorium
RHEcosystemAppEng/dbaas-operator pull request #212
Opened 2022-07-25 19:37 UTC by redhatHameed

added params as a environment variable for dev observatorium to read value from secret and pass to observability cr. 
## Description

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2022-07-26 13:12 UTC, jianrongzhang89 commented
@redhatHameed What about using separate metrics for the creation time stamp itself instead of adding it to each metric (like what kube state metrics does)?  This is because there are multiple metrics for each inventory/instance/connection CR, and in the future, we may want to add additional metrics.

2022-07-26 13:23 UTC, redhatHameed commented
> @redhatHameed What about using separate metrics for the creation time stamp itself instead of adding it to each metric (like what kube state metrics does)? This is because there are multiple metrics for each inventory/instance/connection CR, and in the future, we may want to add additional metrics.

At the moment, we have requirements like, when inventory/connection/instance created, what is the status, who is the provider, so with the single metrics we are getting all the required information. 
if we need to define extra metrics for creation time, then we have to query multiple metrics to get information.

2022-07-26 13:26 UTC, redhatHameed commented
> @redhatHameed Just realized you updated the PR and removed the creation timestamp related changes. Could you update the PR description?

it's there not removed just updated to add timestamp to request duration metrics :)

2022-07-26 14:54 UTC, jianrongzhang89 commented
> 

OK

2022-08-01 15:05 UTC, tchughesiv commented on bundle/manifests/dbaas-operator.clusterserviceversion.yaml
> +                      optional: true
how is this secret created? would these additions make it a requirement for the operator to start?
what happens if it doesn't exist?

2022-08-01 15:20 UTC, tchughesiv commented on bundle/manifests/dbaas-operator.clusterserviceversion.yaml
> +                      optional: true
nm, i see now they're marked as `optional`

2022-08-01 15:49 UTC, jianrongzhang89 commented on controllers/reconcilers/providers_installation/observability-operator.go
> +			if _, err := controllerutil.CreateOrUpdate(ctx, r.client, monitoringStackCR, func() error {
If there is already one monitoring stack CR, why do you need to create a new one? If so it would end with two CRs?

2022-08-01 15:49 UTC, jianrongzhang89 commented on config/samples/secret-dbaas-operator-dev-prom-remote-write.yaml
> +  rhobs-audience: test
Could you add a new line?

2022-08-01 15:54 UTC, redhatHameed commented on controllers/reconcilers/providers_installation/observability-operator.go
> +			if _, err := controllerutil.CreateOrUpdate(ctx, r.client, monitoringStackCR, func() error {
I am trying to update the same CR- `monitoringStackCR = &monitoringStackList.Items[0]` the reason to update the same CR is  if any value change in environment variable, I want update the value accordingly

2022-08-02 15:56 UTC, redhatHameed commented on config/samples/secret-dbaas-operator-dev-prom-remote-write.yaml
> +  rhobs-audience: test
done

2022-08-03 20:01 UTC, xieshenzh requested changes

2022-08-03 20:01 UTC, xieshenzh commented on api/v1alpha1/dbaasplatform_types.go
> +	ObservatoriumConfig ObservatoriumConfig
`PlatformConfig` is supposed to be generic, so can we make this field not so specific to the observability operator?
For example, change the name to `OtherConfigs` and the type to be `map[string]string` or some new interface.

2022-08-04 22:15 UTC, redhatHameed commented on api/v1alpha1/dbaasplatform_types.go
> +	ObservatoriumConfig ObservatoriumConfig
make sense, updated `OtherConfigs   map[ConfigName]OtherConfig` have a review again thanks

2022-08-05 14:52 UTC, xieshenzh requested changes

2022-08-05 14:52 UTC, xieshenzh commented on api/v1alpha1/dbaasplatform_types.go
> +	OtherConfigs   map[ConfigName]OtherConfig
I don't think the keys of the map should be the operator types, because one `PlatformConfig` struct already represents one operator type.
I think the keys of the map should be the configuration properties. For example:
```
dbaasv1alpha1.ObservabilityInstallation: {
		Name:           OBSERVABILITY_NAME,
		CSV:            OBSERVABILITY_CSV,
		DeploymentName: OBSERVABILITY_DEPLOYMENT,
		Image:          OBSERVABILITY_CATALOG_IMG,
		PackageName:    OBSERVABILITY_PKG,
		Channel:        OBSERVABILITY_CHANNEL,
		DisplayName:    OBSERVABILITY_DISPLAYNAME,
		Type:           dbaasv1alpha1.TypeOperator,
		OtherConfigs: map[string]string{
			AuthType:           os.Getenv("AUTH_TYPE"),
			RemoteWritesURL:    os.Getenv("RHOBS_API_URL"),
			RHSSOTokenURL:      os.Getenv("RH_SSO_TOKEN_ENDPOINT"),
			ObservatoriumToken: os.Getenv("RHOBS_TOKEN"),
			AddonName:          os.Getenv("ADDON_NAME"),
			RHOBSSecretName:    fmt.Sprintf("%v-prom-remote-write", os.Getenv("ADDON_NAME")),
		},
	},
```

2022-08-05 15:43 UTC, redhatHameed commented on api/v1alpha1/dbaasplatform_types.go
> +	OtherConfigs   map[ConfigName]OtherConfig
The difference is I am using `map[string]struct{}` which I think is better as we are restricting the params list then  `map[string]string{}`, and it's easy to validate and consume by function like [here](https://github.com/RHEcosystemAppEng/dbaas-operator/blob/fa16d23759df55349e1e7b79a77e440ee79239cb/controllers/reconcilers/providers_installation/observability-operator.go#L66)

2022-08-05 16:03 UTC, xieshenzh commented on api/v1alpha1/dbaasplatform_types.go
> +	OtherConfigs   map[ConfigName]OtherConfig
The code of `OtherConfig` actually restricts all the `PlatformConfig` to use only the params list of the oberservability operator, which would still make `OtherConfigs` specific to the oberservability operator.
For example, if I want to use `OtherConfig` for the cockroach operator, I cannot get rid of the obervability operator params list.
In addition, the `map` will always have one key which is the operator type, so it is unnecessary to use a `map` in this case.
If you want the restrict the behavior of the params list, you could create an interface of `OtherConfig`, and make the obersvability operator params struct implement the interface.

2022-08-05 20:34 UTC, redhatHameed commented on api/v1alpha1/dbaasplatform_types.go
> +	OtherConfigs   map[ConfigName]OtherConfig
removed then OtherConfigs from PlatformConfig and created separate function [Review](https://github.com/RHEcosystemAppEng/dbaas-operator/compare/fa16d23759df55349e1e7b79a77e440ee79239cb..ad38aca862440b31e135a4de07092a75cee09a8e)

2022-08-09 13:38 UTC, jeremyary commented
hey guys, I believe AH has addressed all initial feedback, PTAL? Thanks!

2022-08-11 20:11 UTC, tchughesiv commented on controllers/reconcilers/constants.go
> +		RHOBSSecretName:    fmt.Sprintf("%v-prom-remote-write", os.Getenv("ADDON_NAME")),
what happens if one of these returns empty?

2022-08-11 20:12 UTC, redhatHameed commented
@jianrongzhang89 @jeremyary @tchughesiv @xieshenzh  rebased the PR with main- Please have a another look thanks

2022-08-11 20:15 UTC, redhatHameed commented on controllers/reconcilers/constants.go
> +		RHOBSSecretName:    fmt.Sprintf("%v-prom-remote-write", os.Getenv("ADDON_NAME")),
it will ignore remote writing part in the obseravility CR like [1 ](https://github.com/redhatHameed/dbaas-operator/blob/c27c438ac1759cc71ad599320f17eaa0923fdc0e/controllers/reconcilers/providersinstallation/observability-operator.go#L142)& [2](https://github.com/redhatHameed/dbaas-operator/blob/c27c438ac1759cc71ad599320f17eaa0923fdc0e/controllers/reconcilers/providersinstallation/observability-operator.go#L156)

2022-08-11 20:38 UTC, tchughesiv approved these changes
lgtm

2022-08-11 20:40 UTC, tchughesiv requested changes

2022-08-11 20:40 UTC, tchughesiv commented on config/default/manager-env-images.yaml
> +          value: observability-operator.v0.0.13
was `make generate bundle` run after these changes? i don't see them reflected in the bundle csv.

2022-08-11 21:02 UTC, redhatHameed commented on config/default/manager-env-images.yaml
> +          value: observability-operator.v0.0.13
fixed that @tchughesiv thanks, reflected in CSV file

2022-08-11 21:39 UTC, tchughesiv submitted a review, later dismissed

2022-08-18 15:00 UTC, jeremyary approved these changes

2022-08-18 15:02 UTC, merged