Update env
RHEcosystemAppEng/dbaas-operator pull request #226
Opened 2022-08-29 21:22 UTC by redhatHameed

## Description

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2022-08-30 14:38 UTC, redhatHameed commented
@tchughesiv is there way to ignore this check ->https://github.com/RHEcosystemAppEng/dbaas-operator/runs/8094448512?check_suite_focus=true 

the error happened due these varaiable names 
```
	rhobsRemoteWriteConfigName         = "prom-remote-write-config-secret"
	rhobsTokenKey                      = "rhobs-token"
```

2022-08-30 19:13 UTC, redhatHameed commented
> @tchughesiv is there way to ignore this check ->https://github.com/RHEcosystemAppEng/dbaas-operator/runs/8094448512?check_suite_focus=true
> 
> the error happened due these varaiable names
> 
> ```
> 	rhobsRemoteWriteConfigName         = "prom-remote-write-config-secret"
> 	rhobsTokenKey                      = "rhobs-token"
> ```

adding  //#nosec infront of the code lines fix/ignore that

2022-08-31 14:38 UTC, jianrongzhang89 commented on controllers/reconcilers/providersinstallation/observability-operator.go
> +	if rhobsRemoteWriteConfigSecret.UID == "" {
using errors.IsNotFound() seems to be easier to understand here.

2022-08-31 14:59 UTC, jeremyary commented on .gitignore
> +config/samples/secret-dbaas-operator-dev-prom-remote-write.yaml
is this something other devs will have to populate so they can work locally?

2022-08-31 15:01 UTC, jeremyary requested changes

2022-08-31 15:01 UTC, jeremyary commented on config/samples/installation-for-non-OSD-OCP-environments.yaml
> +apiVersion: operators.coreos.com/v1alpha1
let's keep this over in the wiki instead of code source as either an update for existing page or new one titled something like 'including monitoring'
https://github.com/RHEcosystemAppEng/dbaas-operator/wiki/RHODA-Operator-1-Step-Installation-for-non-OSD-OCP-environments

2022-08-31 15:03 UTC, redhatHameed commented on .gitignore
> +config/samples/secret-dbaas-operator-dev-prom-remote-write.yaml
This is not required, only if other dev wants to test remote observatorium

2022-08-31 15:07 UTC, redhatHameed commented on config/samples/installation-for-non-OSD-OCP-environments.yaml
> +apiVersion: operators.coreos.com/v1alpha1
only reason putting here easy to create and delete the with oc command `oc apply -f ` from wiki we have to download/copy separately every time.

2022-08-31 15:30 UTC, jianrongzhang89 commented on controllers/reconcilers/providersinstallation/observability-operator.go
> +	if rhobsRemoteWriteConfigSecret.UID == "" {
Yes I know. What about changing lines #212-217 to:
if err := r.client.Get(ctx, k8sclient.ObjectKeyFromObject(rhobsRemoteWriteConfigSecret), rhobsRemoteWriteConfigSecret); err != nil {
       if errors.IsNotFound(err) {
             return nil, fmt.Errorf("rhobs remote write secret not found in namespace %v", namespace)
	} 
        return nil, err
 }

2022-08-31 15:44 UTC, redhatHameed commented on controllers/reconcilers/providersinstallation/observability-operator.go
> +	if rhobsRemoteWriteConfigSecret.UID == "" {
done. thanks

2022-08-31 17:41 UTC, jeremyary commented on config/samples/installation-for-non-OSD-OCP-environments.yaml
> +apiVersion: operators.coreos.com/v1alpha1
fair enough!

2022-08-31 17:41 UTC, jeremyary approved these changes

2022-08-31 20:54 UTC, merged