[DBAAS-887] add label selector option for valid DBaaSConnection namespaces
RHEcosystemAppEng/dbaas-operator pull request #233
Opened 2022-09-14 15:37 UTC by tchughesiv

Signed-off-by: Tommy Hughes <tohughes@redhat.com>

## Description

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2022-09-21 19:56 UTC, raffaelespazzoli requested changes

2022-09-21 19:56 UTC, raffaelespazzoli commented on api/v1alpha1/dbaaspolicy_types.go
> +	// Use label selectors to determine namespaces where DBaaSConnections/DBaaSInstances are allowed to reference a policy's inventories.
this is not correct: a label selector is not a map[string]string, the following type should be used: `metav1.LabelSelector` is has utility functions to decide whether something is selected and support expressions.

2022-09-21 20:04 UTC, tchughesiv commented on api/v1alpha1/dbaaspolicy_types.go
> +	// Use label selectors to determine namespaces where DBaaSConnections/DBaaSInstances are allowed to reference a policy's inventories.
tks for the feedback, agreed that makes more sense.

2022-09-22 19:26 UTC, tchughesiv commented on api/v1alpha1/dbaaspolicy_types.go
> +	// Use label selectors to determine namespaces where DBaaSConnections/DBaaSInstances are allowed to reference a policy's inventories.
@raffaelespazzoli better?

2022-09-28 17:35 UTC, jeremyary approved these changes

2022-09-30 00:19 UTC, merged