Add/refine environment setup and run instructions for new team members
RHEcosystemAppEng/dbaas-operator pull request #285
Opened 2022-10-31 13:29 UTC by rhkp

## Description
Refine readme with information that new team member may need to run the dbaas-operator.

## Verification Steps
As covered in the readme.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist (Definition of Done)

~~- [ ] All acceptance criteria specified in JIRA or in issue number have been completed~~
~~- [ ] Unit tests added that prove the fix is effective or the feature works ~~
- [ ] Documentation added for the feature
~~- [ ] all relevant tests are passing~~
~~- [ ] Code Review completed~~
~~- [ ] Verified independently by reviewer~~

2022-10-31 14:08 UTC, tchughesiv requested changes
thanks for the contribs! just a couple things to improve to this PR

2022-10-31 14:08 UTC, tchughesiv commented on README.md
> +* Verify the operator-sdk installation is successful
the SDK will be installed automatically during any make commmand that requires it -
https://github.com/RHEcosystemAppEng/dbaas-operator/blob/fba7a57204dfb7c2f29c9b26710a05d18540d6a0/Makefile#L291-L306

maybe, instead of this section telling the user to install manually, we incorporate `make sdk`? or we improve the above make script to force the proper version be used? I have some ideas on how this might work actually.

2022-10-31 14:08 UTC, tchughesiv commented on README.md
> +- `make catalog-update`
we should probably mention to the user that we already pre-build these images and that, if they just want to deploy the latest code from main... it's already available here -
https://quay.io/repository/ecosystem-appeng/dbaas-operator-dev-catalog?tab=tags

They can find the exact commit they want to deploy based on the commit sha.

2022-10-31 14:09 UTC, tchughesiv commented on README.md
> +- `make catalog-update`
what you've already defined is perfect for active development by a user... but we also offer a way to deploy the latest code without having to build anything.

2022-10-31 14:24 UTC, tchughesiv commented on README.md
> +* Verify the operator-sdk installation is successful
ill be submitting a PR to your branch this morning to help address this

2022-10-31 14:43 UTC, tchughesiv commented on README.md
> +* Verify the operator-sdk installation is successful
https://github.com/rhkp/dbaas-operator/pull/1

2022-10-31 14:43 UTC, tchughesiv commented on README.md
> +* Verify the operator-sdk installation is successful
the above PR likely makes this entire operator-sdk install section unecessary

2022-10-31 15:39 UTC, tchughesiv commented on README.md
> +* Verify the operator-sdk installation is successful
please remove the above SDK section of the README ... the following PR will handle this for the user -
https://github.com/RHEcosystemAppEng/dbaas-operator/pull/286

2022-10-31 16:45 UTC, jianrongzhang89 commented on README.md
> +### Provisioning a Red Hat OCP 4.9 Cluster
=> Provisioning a Red Hat OCP 4.9 Cluster for Development Testing

2022-10-31 16:45 UTC, jianrongzhang89 commented on README.md
> +If you run locally or via direct deploy (no longer recommended), you can create a DBaaSInventory & will receive a DBaaSConnection, but will not see DBaaS console UI and bindable in Topology view.
This statement does not seem to be correct. DBaaSConnection CRs created directly in command line can appear in the developer view in the OpenShift Console.

2022-10-31 16:45 UTC, jianrongzhang89 commented on README.md
> +* Navigate to https://www.mongodb.com/cloud/atlas/register and complete the registration with Red Hat email.
Since this repo is open-sourced, anyone can contribute to the project. So remove "Red Hat Email".

2022-10-31 16:45 UTC, jianrongzhang89 commented on README.md
> +* Request Jianrong Zhang for adding you to the AppEng MongoDB Atlas account.
"Jianrong Zhang" => your organization's MongoDB Atlas administrator

2022-10-31 16:45 UTC, jianrongzhang89 commented on README.md
> +### No longer recommended - Run as a local instance
Running as a local instance is still useful. "No longer recommended" => Alternatively

2022-10-31 16:45 UTC, jianrongzhang89 commented on README.md
> +### No longer recommeneded - Deploy & run on a cluster
Remove "No longer recommended"

2022-10-31 17:10 UTC, rhkp commented on README.md
> +If you run locally or via direct deploy (no longer recommended), you can create a DBaaSInventory & will receive a DBaaSConnection, but will not see DBaaS console UI and bindable in Topology view.
This one was already existing instruction, Option 1: Delete this statement if it is no longer applicable. Option 2: Let me know how does the following rephrase look and suggest changes if needed.

If you run locally or via direct deploy (no longer recommended), you can create a DBaaSInventory.  DBaaSConnection CRs created directly in command line can appear in the developer view in the OpenShift Console.

2022-10-31 17:48 UTC, rhkp commented on README.md
> +### Provisioning a Red Hat OCP 4.9 Cluster
We can choose from one of these options..

Option 1: We can remove this section altogether
Option 2: Rename it with "If you are a Red Hat(er) - Provisioning a Red Hat OCP 4.9 Cluster"

2022-11-01 13:19 UTC, rhkp commented on README.md
> +### No longer recommeneded - Deploy & run on a cluster
Done

2022-11-01 13:19 UTC, rhkp commented on README.md
> +### No longer recommended - Run as a local instance
Done

2022-11-01 13:19 UTC, rhkp commented on README.md
> +* Request Jianrong Zhang for adding you to the AppEng MongoDB Atlas account.
Done

2022-11-01 13:20 UTC, rhkp commented on README.md
> +* Navigate to https://www.mongodb.com/cloud/atlas/register and complete the registration with Red Hat email.
Done

2022-11-01 13:21 UTC, jianrongzhang89 commented on README.md
> +* When you receive the AppEng MongoDB Atlas account invitation, accept it.
Remove "AppEng"

2022-11-01 13:24 UTC, jianrongzhang89 commented on README.md
> +If you run locally or via direct deploy (no longer recommended), you can create a DBaaSInventory & will receive a DBaaSConnection, but will not see DBaaS console UI and bindable in Topology view.
Option #2 looks better. "developer view"=> "the topology view"

2022-11-01 13:31 UTC, rhkp commented on README.md
> +If you run locally or via direct deploy (no longer recommended), you can create a DBaaSInventory & will receive a DBaaSConnection, but will not see DBaaS console UI and bindable in Topology view.
Done

2022-11-01 13:32 UTC, rhkp commented on README.md
> +* When you receive the AppEng MongoDB Atlas account invitation, accept it.
Done

2022-11-02 15:32 UTC, jeremyary commented on README.md
> +### Provisioning a Red Hat OCP 4.9 Cluster
Hmm, so RHPDS is just one way to skin the proverbial cat... I'd like to capture the version prerequisite of an OCP cluster >= v4.10 (I'm consciously omitting 4.9 here, we will drop support for it very soon, likely this release). We don't want to retouch this verbiage with each new OCP version, but we do need to get the version prerequisite across... My 2 cents - let's add a note or prerequisites section to "running the operator" portion that clarifies the version requirement, but let's not worry about documenting how to go about getting one.

2022-11-02 15:33 UTC, jeremyary commented
@tchughesiv I'm happy here, any further thoughts/suggestions from you or can we clear the changed requested marker?

2022-11-02 16:50 UTC, rhkp commented on README.md
> +Recommended way of running the operator is on a OCP 4.9 or higher cluster. You can use Red Hat Demo System to provision a test cluster, which typically is available 2 days extendable upto a week.
Done.

2022-11-02 16:56 UTC, jeremyary approved these changes

2022-11-02 16:56 UTC, merged