DBaaS Inventory Metrics Changes
RHEcosystemAppEng/dbaas-operator pull request #288
Opened 2022-11-08 14:56 UTC by rhkp

## Description
[DBaaS Inventory Metrics Updates](https://issues.redhat.com/browse/DBAAS-983)

## Verification Steps on OpenShift Local

- On fresh Openshift Local instance, in a terminal window login with admin credentials and deploy DBaaS Operator 
```shell
oc apply -f config/samples/installation-for-non-OSD-OCP-environments.yaml
```
- Once the DBaaS Operator is fully installed, expose the Prometheus service and navigate to the prometheus service in the browser
```shell
oc project openshift-dbaas-operator
oc expose svc/prometheus-operated
oc get route
```

- Follow usual process to add provider such as MongoDB Atlas with Org Id, Public Key and Secret. ( Namespace: openshift-dbaas-operator, Database Services -> Database Access )
- Check the prometheus console with dbaas_requests_duration_seconds_bucket, dbaas_requests_duration_seconds_count, dbaas_requests_duration_seconds_sum metrics.
- You may see metric dbaas_requests_error_count in case if there were errors, just in case.
- Delete the installed operator with
```shell
oc delete -f config/samples/installation-for-non-OSD-OCP-environments.yaml
```

## Type of change

- [ ] Enhancement (non-breaking change which adds functionality)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] ~~ Unit tests added that prove the fix is effective or the feature works ~~
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2022-11-08 16:41 UTC, tchughesiv requested changes
thanks for the contribution! i've added a couple comments. also, is there a jira number we can attach to this PR?

2022-11-08 17:13 UTC, tchughesiv requested changes

2022-11-08 17:54 UTC, rhkp commented on controllers/metrics.go
> +	labelEventValueRead      = "read"
Thanks. Done and also addressed linter comments.

2022-11-09 16:15 UTC, tchughesiv approved these changes
lgtm

2022-11-10 18:48 UTC, jeremyary commented on controllers/metrics.go
> +					duration := time.Now().Sub(inventory.CreationTimestamp.Time)
we might need to specify timezone or UTC here so that we're consistent across regions/developers/etc.

2022-11-10 18:48 UTC, jeremyary commented on controllers/metrics.go
> +						duration := time.Now().Sub(inventory.DeletionTimestamp.Time)
same here, if it's not handled by go

2022-11-10 23:33 UTC, rhkp commented on controllers/metrics.go
> +					duration := time.Now().Sub(inventory.CreationTimestamp.Time)
Done.

2022-11-10 23:33 UTC, rhkp commented on controllers/metrics.go
> +						duration := time.Now().Sub(inventory.DeletionTimestamp.Time)
Done

2022-11-10 23:38 UTC, jeremyary approved these changes
lgtm, thanks Kamlesh!

2022-11-10 23:45 UTC, rhkp commented
Thanks @jeremyary & @tchughesiv for reviews and approvals. Can I merge the PR? Please advise.

2022-11-10 23:52 UTC, jeremyary commented
@rhkp yep, was just waiting on the checks to pass. Good to go!

2022-11-10 23:53 UTC, merged