DBAAS-999 Full Provisioning with CockroachDB Provider - data model changes
RHEcosystemAppEng/dbaas-operator pull request #294
Opened 2022-11-23 03:17 UTC by jianrongzhang89

## Description
Implements the data model changes for dbaas operator
See ADR: https://docs.google.com/document/d/1IEgyNOdryWR17cj_QtMsa62ZZtk0Hqdst-NtGGn9EFg/edit#
## Type of change

- [X ] New feature (non-breaking change which adds functionality)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [X ] Code Review completed
- [ ] Verified independently by reviewer

2022-11-29 01:44 UTC, bmozaffa requested changes

2022-11-29 01:44 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +type ParamData struct {
Do we use / care about this data structure, or is it just metadata we ignore? If the former, please use strict definitions that make sense for a given context

2022-11-29 01:44 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	Depends []ParamData `json:"depends,omitempty"`
Dependent parameter? Can you elaborate?

2022-11-29 19:25 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Depends []ParamData `json:"depends,omitempty"`
These are other parameters (such as pricing plan and cloud provider) that must be set for this field to apply and be visible to the user.

2022-11-29 19:25 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type ParamData struct {
Yes this is used. I renamed it to ParameterData.

2022-11-29 19:26 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	Depends []ParamData `json:"depends,omitempty"`
ah ok, so maybe `FieldDependency`?

2022-11-29 19:27 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +type ParamData struct {
That still doesn't tell me, as a reader / reviewer, what this is and what it means. The type, as well as its fields, should have names that relate to DBaaS providers.

2022-11-29 21:14 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type ParamData struct {
@bmozaffa thanks! You are right. The meaning was not clear (I wanted to use the same type for two purposes). I switched to use two types instead:
type DropdownItem struct {
	// Identifier for the value
	Key string `json:"key,omitempty"`

	// Corresponding display value
	Value string `json:"value,omitempty"`
}

// FieldDependency defines the name and value of a field used as a dependency
type FieldDependency struct {
	// Name of the field used as a dependency
	Name string `json:"name,omitempty"`

	// Value of the field used as a dependency
	Value string `json:"value,omitempty"`
}

Let me know what you think.

2022-11-29 21:14 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Depends []ParamData `json:"depends,omitempty"`
Sounds good. Thanks.

2022-11-29 21:33 UTC, bmozaffa requested changes

2022-11-29 21:33 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	Value string `json:"value,omitempty"`
What's key and what's value?

2022-11-29 21:33 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	Value string `json:"value,omitempty"`
What's name and what's value?

2022-11-29 21:41 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Value string `json:"value,omitempty"`
Key is the index for the dropdown item
Value is the display value of the item in the dropdown.

2022-11-29 21:43 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Value string `json:"value,omitempty"`
Name: this is the name of the field used as a dependency, for instance, "cloud_provider".
Value: the value used as a dependency, ie, "AWS" -- this means this dropdown list is only applicable to cloud_provider = "AWS".

2022-11-30 05:04 UTC, bmozaffa requested changes

2022-11-30 05:04 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	Value string `json:"value,omitempty"`
Ok, so use something like FieldName and FieldValue or simply Field and Value instead of Name/Value?

2022-11-30 05:04 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	Value string `json:"value,omitempty"`
Index, as in the order in which it should be sorted? Aren't arrays already sorted? Or if necessary, just call it Index?

2022-11-30 20:18 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Value string `json:"value,omitempty"`
Yes the array is sorted. However, we'd better use the key-value pairs (for instance "AWS" for "Amazon Web Services") than use an integer index. So I prefer to keep it as "key" here.

2022-11-30 20:18 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Value string `json:"value,omitempty"`
Field/ value sounds good to me :)

2022-11-30 20:25 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	Value string `json:"value,omitempty"`
Ok, I was not clear on what you meant by index. Maybe `Value` and `DisplayValue`?

2022-11-30 20:25 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +type ParamData struct {
Thanks, further discussed elsewhere.

2022-11-30 21:23 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	Parameter string `json:"parameter,omitempty"`
Field? We'll need to make sure we're consistent wherever we end up with this.

2022-11-30 21:43 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Parameter string `json:"parameter,omitempty"`
OK. Thanks.

2022-11-30 21:44 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Value string `json:"value,omitempty"`
Yeah, Value/DisplayValue looks much better. Thank you for your suggestion.

2022-11-30 21:56 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	Data []DropdownItem `json:"data,omitempty"`
`Options` instead of `Data`?

2022-11-30 22:40 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
Yes the provider operator provides the dbaasprovider data as a CR (we decided in the beginning of RHODA project to use a CR instead of a configmap). The reason that why we set the status here, is that some of the data can change from time to time (such as available regions to create new clusters) and also since such data can only be retrieved using necessary credentials through the provider accounts, here we use the inventory's controller to "reconcile" such CR and provide the result in the status.

2022-11-30 22:45 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Data []DropdownItem `json:"data,omitempty"`
"Options" sounds good.

2022-11-30 22:46 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
The inventory's controller? Do you mean the provider operator or something else?

Let's think of the Spec/Status as the request/response. Is this data updated by someone other than the party that initially created the CR and filled in the Spec?

2022-11-30 22:54 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderData struct {
What about "FieldOptions"? This structure now is for the list of dropdown options for a field. What aboutnot to have "Provisioning" in the name so that later it might be used for non-provisioning purposes? Please let me know.

2022-11-30 23:08 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderData struct {
In addition, I changed DropdownItem to "Option" which is more generic and can be used for different controls such as dropdown, radio button and checkbox. Please let me know what you think.

2022-11-30 23:18 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
This is the provider operator's inventory reconciler. So it is created and controlled by the provider operator only. Currently, the provider operator creates this CR upon start-up so that the operator gets registered with the DBaaS Operator. However, at this point, the provider operator does not have the credentials needed to populate certain data.   Such credentials only become available when a user creates an inventory, and that's why such data population is deferred to the inventory's reconciler and stored in the status of the CR.

The alternative solution would require the provider operator to use a generic "service account" to access the ISV, so that the dbaasprovider CR is managed by a single reconciled. However, this would make our overall solution a lot more complicated due to the need to maintain such a service account.

Please let me know what you think about the approach proposed.

2022-11-30 23:52 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderData struct {
> What about "FieldOptions"? This structure now is for the list of dropdown options for a field. What aboutnot to have "Provisioning" in the name so that later it might be used for non-provisioning purposes? Please let me know.

It makes sense to not limit this to provisioning... I think DBaaSProviderData is more meaningful than FieldOptions.

2022-11-30 23:53 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	FieldOptions []FieldOptions `json:"fieldOptions,omitempty"`
Should this field (versus the type) then be called ProvisioningFields or similar?

2022-11-30 23:57 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
Service account approach is not possible.

Ok, so what you're saying is that the only difference between initial provider data currently in Spec versus later data currently in status is that the later data was not available to the operator when it was registering itself. That's not a good reason to move that data to Status. It should still be in Spec.

2022-12-01 01:48 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
There are benefits of using the status to store such data - it will allow the operator to set the status conditions to indicate whether this data has been processed successfully, and in the case when it fails to process it, set the error messages accordingly. In addition, this allows the operator to keep track of when the data was processed last time, and decide whether it needs to refresh it.

Normally the spec should only indicate the desired state of the CR, so the spec is static and not good for storing data that can change later.

2022-12-01 01:53 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
Good points, the whole thing is a bit weird, but ok!

2022-12-01 02:15 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderData struct {
OK. Changed back to DBaaSProviderData.

2022-12-01 02:46 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
@xieshenzh I agree this is not a perfect solution, but it would meet the requirements for CockroachDB. If in the future we indeed need to support the case where different credentials would result in a different list of regions we could enhance it for that provider (ie, store such special data in the inventory status) and it can be considered as out of scope for the current task.

About the security concern - this is what we have today and this design does not make it worse. Since the CR is a cluster-level custom resource, users other than the provider operator's service account will need a cluster admin role to modify the data.

2022-12-01 03:03 UTC, xieshenzh commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
It will meet the requirements for CockroachDB today, but CockroachDB could change the retrieved data whenever they like.
And I don't think any users with the permission to read the DBaaSProvider CR should have access to the tenants' data by default.
Are there any important reasons for which we should not store such data in the inventory status now? I think it would be more difficult to move it to the inventory status later.

2022-12-01 03:09 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
Maybe I made some wrong assumptions in my read of this... I assumed the fact that you could only retrieve field values using credentials was a fluke, in that this should be publicly available data and also that it is global in context. Is that not the case? Can we ask cockroach?

If the data is really different per tenant, that is a problem even today, because multiple inventories are supported for cockroach.

2022-12-01 15:41 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
@bmozaffa yes we can follow up with Cockroach for clarification.

2022-12-05 16:14 UTC, xieshenzh commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
It sounds like they are suggesting using static values for the available regions.
I guess that is what they are doing with their own UI.

2022-12-05 16:34 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
What they suggest is that it is fine to cache the data for a certain period of time, but since the data can still change, it is better to have the ability to refresh data than to require restarting of the provider operator itself.

2022-12-05 16:35 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
Let's ask and get an idea of the scale when they say "slowly"... are they adding a new region every 3-4 months? Any other changes, and anything more frequently?

2022-12-05 16:35 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	FieldOptions []FieldOptions `json:"fieldOptions,omitempty"`
Changed to "Options".

2022-12-05 19:49 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
@bmozaffa This what they replied:
"Regions will not be removed from the list. New additions are made irregularly so it's tough to give an indication of how often that might happen - refreshing the cache every week seems reasonable - so your customers would go no longer than 1 week without knowledge of a new region having become available. One big event to keep an eye out for, especially from an ARO perspective, is the addition of Azure regions. This is planned for May/June 2023 timeframe but could come online sooner. "

2022-12-12 16:40 UTC, redhatHameed commented
@jianrongzhang89 we can we add new one or update existing sample example for provider registration under -WDYT ?>https://github.com/RHEcosystemAppEng/dbaas-operator/blob/main/config/samples/dbaas_v1alpha1_dbaasprovider.yaml

2022-12-12 16:45 UTC, xieshenzh commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
If you insist on storing the data in the dbaas provider object, then why not store the data in the spec of the dbaas provider object?
Just modify `InstanceParameterSpec` to store the candidate values, and use the crdb inventory controller to update the spec of the dbaas provider object, it is not immutable. The crdb provider operator creates the dbaas provider object, it can also update the spec of the dbaas provider object. 
It doesn't make sense to set the status of the dbaas provider object with the crdb inventory controller.

2022-12-12 21:09 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderStatus struct {
@xieshenzh I agree the provider data for the dropdown list is better included in the dbaasprovider CR spec instead of the status.

2022-12-12 23:56 UTC, bmozaffa requested changes

2022-12-12 23:56 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +type DBaaSProviderData struct {
With the changes we discussed, we should now move away from the abstract approach and make this very specific to our provisioning page. So should this be called ProvisioningParameter (each is a single param)?

2022-12-12 23:56 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	Field string `json:"field,omitempty"`
Create enum for this, representing the fields we have for provisioning

2022-12-12 23:56 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	Field string `json:"field,omitempty"`
Create enum for this, representing the fields we have for provisioning

2022-12-13 15:34 UTC, jianrongzhang89 commented
> 

Sounds good. Will add one once our design is finalized.

2022-12-13 17:58 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Field string `json:"field,omitempty"`
@bmozaffa currently, different providers already use their own list of parameters (for freetrial provisioning). If we create enum to enforce the list of parameters, we may run into issues when we upgrade to the new RHODA release, as it is possible there are existing CRs with old parameter names defined, and the upgrade will fail unless a data migration is performed. Without the enums, the provider operators could then map both the old and new parameters to the desired one to allow a smooth upgrade.

On the other hand, since for R6 we already plan CRD versioning upgrade, we could add the above migration to the CRD upgrade using the conversion webhook. 

How should we proceed? @jeremyary

2022-12-13 18:24 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Field string `json:"field,omitempty"`
Added.Please review.

2022-12-13 18:24 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Field string `json:"field,omitempty"`
Added the enum. Please review.

2022-12-13 18:43 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	Field string `json:"field,omitempty"`
I see the kube builder annotation for enum... but why not an enum in Go?

2022-12-13 18:47 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	// +kubebuilder:validation:Enum=name;plan;cloud_provider;regions;availability_zones;nodes;machine_type;storage_gib;spend_limit;project
I don't expect you would need this... as we discussed on the call, we are fully moving away from this abstract model of the provider specifying what fields are needed.

2022-12-13 19:05 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	// +kubebuilder:validation:Enum=name;plan;cloud_provider;regions;availability_zones;nodes;machine_type;storage_gib;spend_limit;project
Got it. Updated the PR.

2022-12-13 19:15 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +type FieldName string
Then maybe call the other one something like ProvisioningParamRequirements?

2022-12-13 19:39 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type FieldName string
@bmozaffa I think it is better to keep the other one as ProvisioningParameter. What about changing this one to "ProvisioningParameterName"?

2022-12-13 19:44 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type FieldName string
Changing FieldName to ProvisioningParameter sounds good. What about changing the other one to ProvisioningParameterData?

2022-12-13 19:46 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +type FieldName string
Sure

2022-12-13 19:57 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +type FieldName string
Thanks! PR updated.

2022-12-13 20:12 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	Field string `json:"field,omitempty"`
I'm not sure I understand the migration issues... and ideally we would want to enforce this enum in the CRD as well

2022-12-13 20:13 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	// +kubebuilder:validation:Enum=name;plan;cloud_provider;regions;availability_zones;nodes;machine_type;storage_gib;spend_limit;project
This still remaining?

2022-12-13 20:29 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	// +kubebuilder:validation:Enum=name;plan;cloud_provider;regions;availability_zones;nodes;machine_type;storage_gib;spend_limit;project
No, it is already removed

2022-12-13 20:35 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Field string `json:"field,omitempty"`
We can postpone such CRD validation to a later release if needed. Since the list of parameters and corresponding data is coded in the provider operators rather than provided by end users, the chance if having an invalid parameter can be eliminated as long as we perform the necessary code review and integration tests before release.

2022-12-13 20:51 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	// +kubebuilder:validation:Enum=name;plan;cloud_provider;regions;availability_zones;nodes;machine_type;storage_gib;spend_limit;project
I don't think we're talking about the same thing. The provider should no longer be providing `InstanceParameterSpecs []InstanceParameterSpec` to specify which fields are needed. We know what fields are needed now.

2022-12-13 21:55 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	// +kubebuilder:validation:Enum=name;plan;cloud_provider;regions;availability_zones;nodes;machine_type;storage_gib;spend_limit;project
The InstanceParameterSpec defines which fields are used for the provider, and also provides the display value of for each field. If we do not use it we have to invent something else for such purpose.

2022-12-13 22:11 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	// +kubebuilder:validation:Enum=name;plan;cloud_provider;regions;availability_zones;nodes;machine_type;storage_gib;spend_limit;project
Let's start with looking at lines 124-125 (versus the type itself). The description says `Indicates what parameters to collect from the user interface`. That's no longer a question and we know what parameters should be collected.

2022-12-13 22:26 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	// +kubebuilder:validation:Enum=name;plan;cloud_provider;regions;availability_zones;nodes;machine_type;storage_gib;spend_limit;project
We still want to have the list of parameters that are actually used for each provider. Rather than introducing another type with a boolean flag, it would be easier to simply list the parameters used along with the display value needed by the UX in this existing data structure (For some fields such as spend_limit, it can include the default value the UX can set as well). The ones that are not on the list will be ignored by the UX, indicating that such parameters are not applicable to that provider.

2022-12-13 22:28 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	// +kubebuilder:validation:Enum=name;plan;cloud_provider;regions;availability_zones;nodes;machine_type;storage_gib;spend_limit;project
That's not what we discussed on the call. We need to have code that's easier to understand and use. Our provisioning form is now well defined, and most of the fields are in fact required. Providers should only specify if the optional fields apply to them or not.

2022-12-13 22:47 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	// +kubebuilder:validation:Enum=name;plan;cloud_provider;regions;availability_zones;nodes;machine_type;storage_gib;spend_limit;project
This is a different approach and it will work, but will likely require more amount of implementation work. This is because both the UX and backend provider operators are already implemented to use existing InstanceParameterSpec.

2022-12-16 20:58 UTC, redhatHameed commented on api/v1alpha1/dbaasprovider.go
> +	ProvisioningProject           ProvisioningParameterType = "project"
is this specific project to mongoldb ?

2022-12-16 21:03 UTC, redhatHameed commented on api/v1alpha1/dbaasprovider.go
> +	Project           *ProvisioningParameter `json:"project,omitempty"`
is this specific 'project' to mongoldb ?

2022-12-16 21:03 UTC, tchughesiv commented
looks good... I've added a `hold` label as this change will need to be rebased onto https://github.com/RHEcosystemAppEng/dbaas-operator/pull/296 once it's merged... and all api changes moved to the `v1beta1` dbaasprovider object.

2022-12-18 00:57 UTC, bmozaffa requested changes

2022-12-18 00:57 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	// Default value for the field
Is default value redundant, since there is already a default option in the options list?

2022-12-18 00:57 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +}
Somewhat of an advanced Go design question for anyone with time to dig into it, @jianrongzhang89  @xieshenzh @tchughesiv , but I wonder if there is a way to not repeat these names, once for the enum and once for the list of parameters here. Not worth holding up the PR, though!

2022-12-18 03:09 UTC, xieshenzh commented on api/v1alpha1/dbaasprovider.go
> +}
Do you mean the list of `ProvisioningParameterType` constants?
Maybe, use a real enum like this: https://go.dev/play/p/tozFyBJSJQM

2022-12-18 03:20 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +}
Thanks, @xieshenzh , I think that's a good hint at what would work, but maybe still needs some work to address the issue? The redundancy is that the field names are defined [once](https://github.com/jianrongzhang89/dbaas-operator/blob/full-provisioning/api/v1alpha1/dbaasprovider.go#L70-L81) for ParamType and then listed again for each for [ProvisioningParameterSpec](https://github.com/jianrongzhang89/dbaas-operator/blob/full-provisioning/api/v1alpha1/dbaasprovider.go#L333-L344).

2022-12-19 15:28 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	// Default value for the field
The default value is used for parameters that do not have dropdown options, for instance, spend limit. The default option is for fields that are displayed as dropdowns.

2022-12-19 15:29 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Project           *ProvisioningParameter `json:"project,omitempty"`
Yes, "project" is for mongo, and it can be used as team_id for crunchy later.

2022-12-19 15:38 UTC, redhatHameed commented on api/v1alpha1/dbaasprovider.go
> +	Project           *ProvisioningParameter `json:"project,omitempty"`
can we make something like, `Team Project`  so this will work for both WDYT?

2022-12-19 17:11 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	Field string `json:"field,omitempty"`
@tchughesiv can you clarify this for us? I believe if a CR with old version is provided, that will be taken care of, by the conversion webhook, and we don't need to disable validation for this, right?

2022-12-19 17:25 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +}
@xieshenzh @bmozaffa this sounds good. Updated the PR.

2022-12-19 17:28 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Field string `json:"field,omitempty"`
@bmozaffa now with the new data model,  CRD validation for the list of fields should be fine. I updated the PR accordingly.

2022-12-19 17:28 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Project           *ProvisioningParameter `json:"project,omitempty"`
This sounds good to me. Updated.

2022-12-19 18:04 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +}
I'm not sure what you're trying to achieve here... my (low priority) concern was that the list of parameters was repeated twice (see my links above). Now it is repeated three times: [here](https://github.com/jianrongzhang89/dbaas-operator/blob/full-provisioning/api/v1alpha1/dbaasprovider.go#L82-L93) and [here](https://github.com/jianrongzhang89/dbaas-operator/blob/full-provisioning/api/v1alpha1/dbaasprovider.go#L337-L348) and [here](https://github.com/jianrongzhang89/dbaas-operator/blob/full-provisioning/api/v1alpha1/dbaasprovider.go#L358-L369)

2022-12-19 19:17 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +}
@bmozaffa my bad. Fixed.

2022-12-19 19:23 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +}
Thoughts, @xieshenzh ?

2022-12-19 20:23 UTC, xieshenzh commented on api/v1alpha1/dbaasprovider.go
> +}
I think the constants are supposed to be used by the provider operators, which improves the usability of the API and the readability of the provider operator code.
If we don't care about the usability or readability, we don't really need the constants.
On the other hand, I am not sure if there are other good options. 
I don't think it is easy to design a function which outputs the field name in the struct, while the input is the field value or reference. If we use the index of field in the struct as the input, the usability and readability will not be good.

Another option is to remove the names in the `ProvisioningParametersSpec` instead of the constants.
The `ProvisioningParametersSpec` is created by the provider operators and used by the UX code internally.
We can change it to be a list a parameters as it used to be, with which we won't need the names in the code.

2022-12-19 20:30 UTC, xieshenzh commented on api/v1alpha1/dbaasprovider.go
> +}
There is another option, which is to create a code generator to generate the constants instead of hardcoding them here in the file.

2022-12-19 20:33 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +}
No, that's fine, don't need to go to those lengths. However, I'm not sure about where we've ended up. @jianrongzhang89 you don't even seem to be using `ProvisioningParameterType` in the current design?

2022-12-19 20:48 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +}
@bmozaffa The latest design does not use ProvisioningParameterType directly. However, the const values defined for ProvisioningParameterType will be used by the provider operators to convert from common fields to operator's own parameters so it is still useful. What do you think?

2022-12-20 00:21 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +}
Yeah, I think that's missing the point. I want an enum that enforces the design as well as helps the user understand what goes where.

Ok, so assuming we have a simple string enum:
```
const (
	ProvisioningName ProvisioningParamField = "Name"
	ProvisioningPlan = "Plan"
	ProvisioningCloudProvider = "CloudProvider"
	ProvisioningRegions = "Regions"
	ProvisioningAvailabilityZones = "AvailabilityZones"
	ProvisioningNodes = "Nodes"
	ProvisioningMachineType = "MachineType"
	ProvisioningStorageGib = "StorageGib"
	ProvisioningSpendLimit = "SpendLimit"
	ProvisioningTeamProject = "TeamProject"
	ProvisioningLocationLabel = "LocationLabel"
	ProvisioningHardwareLabel = "HardwareLabel"
)
```

Then it definitely needs to be used in field dependency:

```
type FieldDependency struct {
	Field ProvisioningParamField `json:"field,omitempty"`
```

and I understand that it can't be used in our struct definition, but what if we had no struct at all, and since you're making everything optional there anyway, could we have this under DBaaSProviderSpec?

```ProvisioningParametersSpec map[ProvisioningParamField]ProvisioningParametersSpec 'json:"provisioningParametersSpec,omitempty"```

2022-12-20 18:00 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +}
Thanks, @jianrongzhang89   To be clear, I don't know and haven't tried to understand any downsides of going this route, so let me know what you think, and you too, @xieshenzh

2022-12-20 18:26 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +}
@bmozaffa It sounds like an excellent idea to me :). I updated the PR accordingly. Please take a look again. Meanwhile, I am working on the crdb operator implementation based on this one and see how it goes.

2022-12-20 20:52 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +}
@bmozaffa this is the cockroach CR populated by the CRDB operator:
https://gist.github.com/jianrongzhang89/a44ae85cb872a71295fd00420ef42531

2022-12-21 18:01 UTC, bmozaffa approved these changes

2022-12-21 18:28 UTC, xieshenzh commented on api/v1alpha1/dbaasprovider.go
> +	ProvisioningPlan              ProvisioningParameterType = "plan"
`plan` is what we are going to use to represent the database engine type for RDS, right? @jeremyary @jianrongzhang89

2022-12-21 18:29 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	ProvisioningPlan              ProvisioningParameterType = "plan"
No, and I think we're missing DatabaseType or whatever we want to call it.

2022-12-21 20:43 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	ProvisioningPlan              ProvisioningParameterType = "plan"
@bmozaffa @xieshenzh OK. So use "databaseType"? if so I will add it.

2022-12-21 20:47 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	ProvisioningPlan              ProvisioningParameterType = "plan"
No strong opinion here, but basically something like that, which would apply to AWS, GCP and Azure services and/or anyone else who isn't doing just a single type of database

2022-12-22 15:48 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	ProvisioningPlan              ProvisioningParameterType = "plan"
@bmozaffa @xieshenzh PR updated. Please take another look.

2022-12-22 19:58 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	ProvisioningPlan              ProvisioningParameterType = "plan"
Looks good to me!

2023-01-03 15:28 UTC, redhatHameed submitted a review, later dismissed
lgtm

2023-01-05 21:49 UTC, bmozaffa requested changes

2023-01-05 21:49 UTC, bmozaffa commented on api/v1alpha1/dbaasprovider.go
> +	// If default values are present, the field is displayed as a text input field.
Instead of duplicating the structure for text input field, how about you rename ProvisioningParameterOptions to something like ConditionalProvisioningParameters, and rename DefaultOption to DefaultValue? Then if `Options []Option` is not provided, it's an input field. If it is provided, DefaultValue is the default drop down option, and its DisplayValue is already known from the array anyway.

Still leave the ambiguity, but that's the same as before/now, and I think ok.

2023-01-05 21:58 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	// If default values are present, the field is displayed as a text input field.
I used the DefaultOption instead of DefaultValue as requested by @olavtar for the simplicity of the UX implementation so that the UX can set the defaultOption in the dropdown without calculating the defaultvalue based on its key first. @olavtar Are you OK with what @bmozaffa suggested above?

2023-01-05 22:23 UTC, olavtar commented on api/v1alpha1/dbaasprovider.go
> +	// If default values are present, the field is displayed as a text input field.
@jianrongzhang89 sure, we can try that.

2023-01-06 02:08 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	// If default values are present, the field is displayed as a text input field.
@bmozaffa updated based on your suggestion.

2023-01-06 05:06 UTC, bmozaffa approved these changes

2023-01-09 17:59 UTC, olavtar approved these changes

2023-01-16 19:25 UTC, jianrongzhang89 commented
This PR is replaced by https://github.com/RHEcosystemAppEng/dbaas-operator/pull/308

2023-01-16 19:26 UTC, closed without merging