DBAAS-999 Full Provisioning with CockroachDB Provider - data model changes and v1beta1 support
RHEcosystemAppEng/dbaas-operator pull request #305
Opened 2023-01-11 15:17 UTC by jianrongzhang89

## Description
This PR includes the data model changes for full provisioning of CRDB and RDS clusters in PR (https://github.com/RHEcosystemAppEng/dbaas-operator/pull/294) and adoption of v1beta1 APIs with the following additional changes:
1) Add a flag DBaaSAPIVersion to DBaaSProviderSpec to indicate the DBaaS API version (v1alpha1 or v1beta1) the provider supports.
2) Change DBaaS Inventory, Instance and Connection reconcilers so that the corresponding version (v1alpha1 or v1beta1)  of provider custom resources are created.
3) Unit test cases updated.

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2023-01-11 15:29 UTC, tchughesiv requested changes
good stuff... i realize its still in draft but wanted to put some thoughts down.

2023-01-11 15:29 UTC, tchughesiv commented on api/v1alpha1/dbaasprovider_conversion.go
> +	dst.Status = DBaaSProviderStatus{}
why aren't we converting src status?

2023-01-11 15:29 UTC, tchughesiv commented on Makefile
> +#	$(YQ) 'del(.spec.conversion.webhook.clientConfig.service)' -i bundle/manifests/dbaas.redhat.com_dbaasproviders.yaml
Please rebase on the latest code base to clean up these leftover yq references

2023-01-11 15:29 UTC, tchughesiv commented on api/v1beta1/dbaasprovider.go
> +
what if, instead, we offered an optional 'groupVersion' field for providers to set. This would allow us to support new providers dynamically going forward. For example AcmeDB could set:
```yaml
spec:
  groupVersion: database.acme.io/v1
```
Would this them give our operator everything it needs to manage provider connections/instances, etc?

2023-01-11 15:29 UTC, tchughesiv commented on api/v1alpha1/dbaasprovider_conversion.go
> -	}
why aren't we accounting for `InstanceParameterSpecs`? should these instead convert to/from `ProvisioningParameters`?

2023-01-13 13:41 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider_conversion.go
> +	dst.Status = DBaaSProviderStatus{}
Because v1alpha1 version of provider CR does not use status.

2023-01-13 13:43 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider_conversion.go
> -	}
Actually most of fields in v1alpha1 InstanceParameterSpecs are not used at all except project for mongo and engine for  RDS. Those unused fields are not supported for v1beta1, so their conversion is meaningless except for the two fields used.

2023-01-13 13:43 UTC, jianrongzhang89 commented on Makefile
> +#	$(YQ) 'del(.spec.conversion.webhook.clientConfig.service)' -i bundle/manifests/dbaas.redhat.com_dbaasproviders.yaml
Done

2023-01-13 13:44 UTC, jianrongzhang89 commented on api/v1beta1/dbaasprovider.go
> +
Yes. Changed DBaaSAPIVersion to GroupVersion.

2023-01-13 15:15 UTC, tchughesiv requested changes

2023-01-13 15:15 UTC, tchughesiv commented on api/v1alpha1/dbaasprovider_conversion.go
> -	}
are none of the fields used? if _any_ are still used we have to convert them...

2023-01-15 23:33 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider_conversion.go
> +	dst.Status = DBaaSProviderStatus{}
Yes. The code won't compile:
# github.com/RHEcosystemAppEng/dbaas-operator/api/v1alpha1
api/v1alpha1/dbaasprovider_conversion.go:192:38: too many values in DBaaSProviderStatus{...}

2023-01-15 23:34 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider_conversion.go
> -	}
You are right. Some fields are still used. I updated the conversion logic accordingly.

2023-01-16 14:59 UTC, tchughesiv commented on Makefile
> +#	$(YQ) 'del(.spec.conversion.webhook.clientConfig.service)' -i bundle/manifests/dbaas.redhat.com_dbaasproviders.yaml
if you can't figure out how to properly rebase, you might need to create a new branch based on the latest code and then cherry-pick your changes over... start a new PR or reset this branch HEAD on that new fixed PR

2023-01-16 15:04 UTC, tchughesiv requested changes

2023-01-16 15:04 UTC, tchughesiv commented on api/v1alpha1/dbaasconnection_conversion.go
> +}
do these changes have anything to do w/ the goal of this PR? if not, please revert.

2023-01-16 15:04 UTC, tchughesiv commented on api/v1alpha1/dbaasinventory_conversion.go
> +}
do these changes have anything to do w/ the goal of this PR? if not, please revert.

2023-01-16 18:40 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasconnection_conversion.go
> +}
Yes, these two functions are used by the provider operators to do the conversion. I added here as he same function can be called by each provider that supports v1beta1.

2023-01-16 18:41 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasinventory_conversion.go
> +}
Same as above - used by provider operators.

2023-01-16 18:43 UTC, jianrongzhang89 commented on Makefile
> +#	$(YQ) 'del(.spec.conversion.webhook.clientConfig.service)' -i bundle/manifests/dbaas.redhat.com_dbaasproviders.yaml
Yes I had trouble with it. I will try as you suggested.

2023-01-16 19:24 UTC, jianrongzhang89 commented
This PR is replaced by https://github.com/RHEcosystemAppEng/dbaas-operator/pull/308.

2023-01-16 19:25 UTC, closed without merging