DBAAS-999 Full Provisioning with CockroachDB Provider - data model changes and v1beta1 support
RHEcosystemAppEng/dbaas-operator pull request #308
Opened 2023-01-16 19:24 UTC by jianrongzhang89

This PR replaces https://github.com/RHEcosystemAppEng/dbaas-operator/pull/305 which had rebasing issues.
This PR includes the data model changes for full provisioning of CRDB and RDS clusters in PR (https://github.com/RHEcosystemAppEng/dbaas-operator/pull/294) and adoption of v1beta1 APIs with the following additional changes:

Add a flag DBaaSAPIVersion to DBaaSProviderSpec to indicate the DBaaS API version (v1alpha1 or v1beta1) the provider supports.
Change DBaaS Inventory, Instance and Connection reconcilers so that the corresponding version (v1alpha1 or v1beta1) of provider custom resources are created.
Unit test cases updated.

## Description

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2023-01-16 19:57 UTC, redhatHameed commented on api/v1alpha1/dbaasinstance_conversion.go
> +		case "project":
adding crunchy case here for team ?

2023-01-16 19:57 UTC, redhatHameed commented on api/v1alpha1/dbaasinstance_conversion.go
> +		case v1beta1.ProvisioningTeamProject:
case for team for crunchy Provider ?

2023-01-16 19:57 UTC, redhatHameed commented on api/v1alpha1/dbaasprovider_conversion.go
> +		"TeamID":   v1beta1.ProvisioningTeamProject,
does cockroach has teamId ?

2023-01-16 19:57 UTC, redhatHameed commented on bundle/manifests/dbaas-operator.clusterserviceversion.yaml
> +                  value: quay.io/jianrzha/ccapi-k8s-operator-catalog:v0.0.5-dev
make sure revert this

2023-01-16 19:57 UTC, redhatHameed commented on bundle/manifests/dbaas-operator.clusterserviceversion.yaml
> +  - image: quay.io/jianrzha/ccapi-k8s-operator-catalog:v0.0.5-dev
revert personal quay once we get official image image

2023-01-17 19:19 UTC, xieshenzh commented on api/v1alpha1/dbaasinstance_conversion.go
> +		case "engine":
```suggestion
		case "Engine":
```
It should be `Engine`: https://github.com/RHEcosystemAppEng/rds-dbaas-operator/blob/19e0d6bfb985cfb82e35ecd9b4ac94d6b1d1aa4f/controllers/rdsinstance_controller.go#L55

2023-01-18 02:44 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider_conversion.go
> +		"TeamID":   v1beta1.ProvisioningTeamProject,
No. This is for crunchy instead. Corrected.

2023-01-18 02:44 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasinstance_conversion.go
> +		case v1beta1.ProvisioningTeamProject:
Code updated.

2023-01-18 02:44 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasinstance_conversion.go
> +		case "engine":
Corrected.

2023-01-18 14:54 UTC, tchughesiv requested changes

2023-01-18 14:54 UTC, tchughesiv commented on api/v1alpha1/dbaasinstance_conversion.go
> +		return err
why are we adding api calls to the conversion logic? and why are we returning errors?

this seems like validation logic to me. if it is, it should go in a validation webhook instead.

2023-01-18 14:59 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasinstance_conversion.go
> +		return err
This is because in order to have a correct conversion, we will need to know the provider name, for instance, ProjectName in mongo and TeamID in Crunchy for v1alpha1 are both mapped to "TeamProject" in v1beta1. In order to find the provider name, we need to fetch the inventory first.

2023-01-20 23:58 UTC, redhatHameed commented
@jianrongzhang89 I think you need rebase on main branch ![image](https://user-images.githubusercontent.com/41960152/213825581-03e41e06-fa3d-4c08-bc9a-4481b0cfbd99.jpeg)

2023-01-23 13:28 UTC, jianrongzhang89 commented
> @jianrongzhang89 I think you need rebase on main branch ![image](https://user-images.githubusercontent.com/41960152/213825581-03e41e06-fa3d-4c08-bc9a-4481b0cfbd99.jpeg)

I ran into rebasing issues, so I created another PR to replace this PR:
https://github.com/RHEcosystemAppEng/dbaas-operator/pull/319.

This PR is closed.

2023-01-23 13:28 UTC, closed without merging