DBAAS-999 Full Provisioning with CockroachDB Provider - data model changes and support v1beta1 API
RHEcosystemAppEng/dbaas-operator pull request #319
Opened 2023-01-23 13:26 UTC by jianrongzhang89

…anges: support v1beta1 API version

## Description

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2023-01-23 14:57 UTC, tchughesiv requested changes

2023-01-23 14:57 UTC, tchughesiv commented on api/v1beta1/dbaasprovider.go
> +	// DBaaS API group version supported by the provider
should we change this description to something like -
`API group version supported by the provider`

this doesn't have to be a `dbaas.redhat.com` type of apiversion correct? this could be `database.mongodb.io` or something similar? We need be sure to support whatever api `groupversion` the provider choses to set here. 

code like the following might be a start if we don't already support this? 
```go
gv, err := schema.ParseGroupVersion(provider.spec.GroupVersion)
if err != nil {
    return nil, err
}
newInv := unstructured.Unstructured{}
newInv.SetGroupVersionKind(gv.WithKind(provider.spec.InventoryKind))
```
please also add a unit test to cover this alternative groupversion scenario, if one doesn't already exist... i didn't see any though.

2023-01-24 01:29 UTC, tchughesiv commented on api/v1beta1/dbaasprovider_webhook.go
> +	return schema.GroupVersion{
would it be possible to just return the v1alpha1 api GroupVersion directly?
```go
          return v1alpha1.GroupVersion
```

2023-01-24 01:29 UTC, tchughesiv commented on api/v1beta1/dbaasprovider_webhook.go
> +		if err == nil {
just some items to discuss... not sure we want to do any of it but worth thinking about:
 - should we let an admin know about this error?
 - instead of making assumptions when this field isn't set, maybe set a default for this a field w/ a CRD default? could also set via conversion webhook logic.

2023-01-24 22:52 UTC, tchughesiv commented on api/v1beta1/dbaasprovider.go
> +	// DBaaS API group version supported by the provider
sure, but can't a provider CR have object components based on our data structures, without using our `dbaas.redhat.com` group or version? Why should force the provider to support objects with redhat in the group name? The CRD GVK should have no bearing on what you've stated.

2023-01-25 03:18 UTC, jianrongzhang89 commented on api/v1beta1/dbaasprovider.go
> +	// DBaaS API group version supported by the provider
That was the result of our earlier decision to keep our solution simple. It is possible in the future we may want such other group versions, but this won't be in the scope of the current work.

Please be aware the groupversion field added here is NOT to indicate the group version of the provider API. Rather, it is used to indicate the group version of the DBaaS API the provider supports.

2023-01-25 03:19 UTC, jianrongzhang89 commented on api/v1beta1/dbaasprovider_webhook.go
> +		if err == nil {
Good idea. I added the default as part of the conversion webhook logic.

2023-01-25 16:55 UTC, tchughesiv commented on api/v1beta1/dbaasprovider_webhook.go
> +		if err == nil {
hmm... should a default be added to v1beta1 schema as well? instead of conversion?
https://book.kubebuilder.io/reference/markers/crd-validation.html
```go
//+kubebuilder:default:=<any>
```

2023-01-25 20:41 UTC, jianrongzhang89 commented on api/v1beta1/dbaasprovider_webhook.go
> +		if err == nil {
Yes. Added the default.

2023-01-25 21:19 UTC, tchughesiv requested changes

2023-01-25 21:19 UTC, tchughesiv commented on api/v1beta1/dbaasprovider.go
> +	// DBaaS API group version supported by the provider
if we're setting a default and it appears to be a required field for functionality... should we make this required?

2023-01-25 21:19 UTC, tchughesiv commented on api/v1beta1/dbaasprovider_webhook.go
> +	return schema.GroupVersion{
if we're setting default and setting in conversion, is this block of code necessary?

2023-01-25 21:19 UTC, tchughesiv commented on api/v1beta1/dbaasprovider.go
> +	// DBaaS API group version supported by the provider
also, once required and with default being set... is the new conversion logic around this field necessary anymore?

2023-01-26 15:40 UTC, jianrongzhang89 commented on api/v1beta1/dbaasprovider.go
> +	// DBaaS API group version supported by the provider
Yes I tested it and found it is still required. This is because the conversion webhook essentially overrides the CRD validation and it it will end up the field to get set to empty if the conversion logic does not set the groupVersion field directly.

2023-01-26 16:05 UTC, tchughesiv requested changes
looking good! just a couple more things

2023-01-26 16:05 UTC, tchughesiv commented on api/v1alpha1/dbaasprovider_conversion_test.go
> +			assertProvidersEqual(&src, &dst)
why this change?

2023-01-26 16:05 UTC, tchughesiv commented on api/v1alpha1/dbaasprovider_conversion.go
> +	dst.Spec.GroupVersion = GroupVersion.String() // Set to v1alpha1 version
we need a unit test check for this... at the very least verifying this is properly set in the "intermediate" v1beta1 object. ideally, we could see a reversed conversion where v1alpha1 becomes the "intermediate" and we don't lose any of the new fields on the other side. Maybe in the "src" object, this field is instead set to dbaas.group.com/v1beta1 ?

2023-01-26 16:05 UTC, tchughesiv commented on api/v1beta1/dbaasprovider.go
> +	// DBaaS API group version supported by the provider
thanks

2023-01-26 18:30 UTC, xieshenzh commented on config/default/manager-env-images.yaml
> +              value:  quay.io/jianrzha/ccapi-k8s-operator-catalog:v0.0.5-dev
Are we supposed to use your image for now?

2023-01-26 18:59 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider_conversion_test.go
> +			assertProvidersEqual(&src, &dst)
This is because in v1alpha1, Spec.InstanceParamterSpecs is an array. When the provider CR is converted to v1beta1 and then converted back, the sequence of the parameters in the array is not guaranteed to be the same, and consequently, using deepEqual to compare the 2 objects will fail.  I used assertProvidersEqual() to get around this issue by converting the array to a map and deep equal for go maps is not impacted the order of the elements.

2023-01-26 19:04 UTC, jeremyary commented on config/default/manager-env-images.yaml
> +              value:  quay.io/jianrzha/ccapi-k8s-operator-catalog:v0.0.5-dev
good catch!

2023-01-26 19:12 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider_conversion.go
> +	dst.Spec.GroupVersion = GroupVersion.String() // Set to v1alpha1 version
Good idea. Checking the intermediate object is helpful. We can not set it in the src object though, as the field does not exist in v1alpha1.

2023-01-26 19:18 UTC, jianrongzhang89 commented on config/default/manager-env-images.yaml
> +              value:  quay.io/jianrzha/ccapi-k8s-operator-catalog:v0.0.5-dev
I reverted all references of devt images to existing release images. Once we have new provider images ready we will update the env config file to point to the new images.

2023-01-26 19:26 UTC, tchughesiv commented on api/v1alpha1/dbaasprovider_conversion_test.go
> +			assertProvidersEqual(&src, &dst)
thanks

2023-01-26 19:26 UTC, tchughesiv commented on config/default/manager-env-images.yaml
> +              value:  quay.io/jianrzha/ccapi-k8s-operator-catalog:v0.0.5-dev
do we need to wait to merge this code? shouldn't an updated provider image be part of this PR?

2023-01-26 19:42 UTC, tchughesiv submitted a review, later dismissed
aside from provider image decision, lgtm

2023-01-26 19:42 UTC, jeremyary commented on config/default/manager-env-images.yaml
> +              value:  quay.io/jianrzha/ccapi-k8s-operator-catalog:v0.0.5-dev
my fault, didn't really think on implications here. Likely not a bad idea to keep your functional image until we get one from CRDB and then we can update with a quick PR after. Apologies!

2023-01-26 20:02 UTC, jianrongzhang89 commented on config/default/manager-env-images.yaml
> +              value:  quay.io/jianrzha/ccapi-k8s-operator-catalog:v0.0.5-dev
OK as we discussed lets use the devt build for CRDB image for now.

2023-01-26 20:43 UTC, redhatHameed approved these changes
lgtm

2023-01-26 20:50 UTC, redhatHameed commented
verified on cluster able create the DEDICATED successfully. 
```apiVersion: dbaas.redhat.com/v1beta1
kind: CrdbDBaaSInstance
metadata:
  resourceVersion: '11755382'
  name: ahameed
  uid: 1d107b84-e974-45c4-97f8-88c6c32ba062
  creationTimestamp: '2023-01-26T17:44:15Z'
  generation: 1
  managedFields:
    - apiVersion: dbaas.redhat.com/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"crdbdbaasinstance.dbaas.redhat.com/cluster"': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"9af56726-2f3c-4792-98e6-0c3065ae0e37"}': {}
        'f:spec':
          .: {}
          'f:inventoryRef':
            .: {}
            'f:name': {}
            'f:namespace': {}
          'f:provisioningParameters':
            .: {}
            'f:cloudProvider': {}
            'f:machineType': {}
            'f:name': {}
            'f:nodes': {}
            'f:plan': {}
            'f:regions': {}
            'f:storageGib': {}
      manager: manager
      operation: Update
      time: '2023-01-26T17:44:15Z'
    - apiVersion: dbaas.redhat.com/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
          'f:instanceID': {}
          'f:instanceInfo':
            'f:createAt': {}
            'f:operationStatus': {}
            'f:regions.1.name': {}
            .: {}
            'f:updateAt': {}
            'f:cloudProvider': {}
            'f:creatorId': {}
            'f:numOfRegions': {}
            'f:cockroachVersion': {}
            'f:regions.1.sqlDns': {}
            'f:state': {}
            'f:plan': {}
          'f:phase': {}
      manager: manager
      operation: Update
      subresource: status
      time: '2023-01-26T18:46:31Z'
  namespace: openshift-dbaas-operator
  ownerReferences:
    - apiVersion: dbaas.redhat.com/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: DBaaSInstance
      name: ahameed
      uid: 9af56726-2f3c-4792-98e6-0c3065ae0e37
  finalizers:
    - crdbdbaasinstance.dbaas.redhat.com/cluster
spec:
  inventoryRef:
    name: my-db-provider-account-crdb
    namespace: openshift-dbaas-operator
  provisioningParameters:
    cloudProvider: AWS
    machineType: m5.large
    name: ahameed
    nodes: '3'
    plan: DEDICATED
    regions: us-east-1
    storageGib: '15'
status:
  conditions:
    - lastTransitionTime: '2023-01-26T18:22:46Z'
      message: Ready
      reason: Ready
      status: 'True'
      type: ProvisionReady
  instanceID: 50820275-03a8-4be7-af2c-b2ab37a68601
  instanceInfo:
    numOfRegions: '1'
    cockroachVersion: v22.2.3
    cloudProvider: AWS
    regions.1.sqlDns: ahameed-hcc.aws-us-east-1.cockroachlabs.cloud
    creatorId: ea1d2f94-9c86-488d-8c7d-563b77060632
    plan: DEDICATED
    createAt: '2023-01-26 17:44:15.690894 +0000 UTC'
    state: CREATED
    regions.1.name: us-east-1
    operationStatus: CLUSTER_STATUS_UNSPECIFIED
    updateAt: '2023-01-26 18:46:21.920796 +0000 UTC'
  phase: Ready```

2023-01-26 20:52 UTC, merged