DBAAS-1170: workaround to the rds-controller upgrade issue for release 0.0.4
RHEcosystemAppEng/dbaas-operator pull request #330
Opened 2023-01-31 20:37 UTC by xieshenzh

## Description

The aws `rds-controller` requires a configuration configmap and a credentials secret to finish install and upgrade.
The `rds-dbaas-operator` will scale it down to avoid this issue when installation, but during upgrade the `rds-dbaas-operator` is deleted. `rds-controller` will auto-upgrade,`rds-dbaas-operator` won't be installed until the `rds-controller` upgrade finishes or deleted. 

The workaround is to create dummy aws secret and configmap if not exist during the `dbaas-operator` controllers installation. `ack-controller` and `rds-dbaas-operator` start upgrading after the `dbaas-operator` installation finishes.

## Verification Steps

Tested 3 scenarios:
1. fresh installation, create provider account for RDS, then create provider account for RDS
2. install v0.0.3, create provider account for RDS on v0.0.3, then upgrade to v0.0.4
3. install v0.0.3, not create provider account for RDS, then upgrade to v0.0.4 and create provider account for RDS

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2023-01-31 20:58 UTC, xieshenzh commented
Overall coverage for the file is ~50%, but for the new code I added it is 73.3% . 

![image](https://user-images.githubusercontent.com/42279951/215881193-8b664991-5858-4219-80e0-ca882693f18b.png)

2023-01-31 21:00 UTC, tchughesiv reviewed
thanks for the contrib! I have concerns about memory caching/leaks related to configmaps & secrets. Those are the 2 biggest offenders and we've had to take precaution to avoid CM watches in the past. With regard to secrets, while we do watch them... we take precautions like the following -
https://github.com/RHEcosystemAppEng/dbaas-operator/blob/346d6c647ba154d9c44effdfd4c0fd7abb726a5e/main.go#L124-L127

2023-01-31 21:04 UTC, xieshenzh commented
> thanks for the contrib! I have concerns about memory caching/leaks related to configmaps & secrets. Those are the 2 biggest offenders and we've had to take precaution to avoid CM watches in the past. With regard to secrets, while we do watch them... we take precautions like the following -
> 
> https://github.com/RHEcosystemAppEng/dbaas-operator/blob/346d6c647ba154d9c44effdfd4c0fd7abb726a5e/main.go#L124-L127
> 
> I worry, with a change like this... we'd have to worry about memory leaks again or, at the very least... this would prompt some intensive performance testing/sessions.

Are you suggesting we remove the watch permission and disable cache for configmap as well?

2023-01-31 21:08 UTC, tchughesiv commented
@xieshenzh at the very least, yes. we'll also need broader team discussion

2023-01-31 21:10 UTC, tchughesiv commented
@xieshenzh probably don't need the `list` perm either

2023-02-01 17:22 UTC, tchughesiv requested changes

2023-02-01 17:22 UTC, tchughesiv commented on main.go
> +			&corev1.ConfigMap{},
please add this to the test suites as well...
here - 
https://github.com/RHEcosystemAppEng/dbaas-operator/blob/346d6c647ba154d9c44effdfd4c0fd7abb726a5e/controllers/suite_test.go#L124-L127
and here -
https://github.com/RHEcosystemAppEng/dbaas-operator/blob/346d6c647ba154d9c44effdfd4c0fd7abb726a5e/api/v1beta1/webhook_suite_test.go#L116-L119

2023-02-01 18:08 UTC, xieshenzh commented on main.go
> +			&corev1.ConfigMap{},
Done

2023-02-01 18:13 UTC, tchughesiv approved these changes
lgtm

2023-02-01 18:14 UTC, merged