DRAFT: Remove Red Hat branding and added downstream docs
RHEcosystemAppEng/dbaas-operator pull request #353
Opened 2023-03-10 20:36 UTC by ritz303

## Description
Remove Red Hat branding from documentation and ported over the downstream content.

Fixes: Jira [DBAAS-1232](https://issues.redhat.com/browse/DBAAS-1232)

## Type of change
- [ ] Content edits to the YAML QSG files.
- [ ] Ported over the downstream Quick Start Guide and Reference Guide.

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2023-03-13 04:57 UTC, mrrajan commented on controllers/reconcilers/quickstartinstallation/connecting-an-application-to-a-database-instance-using-the-topology-view-quick-start.yaml
> +  prerequisites: ["Access to the OpenShift console.", "Installation of the OpenShift Database Access add-on.", "A cloud-hosted database provider added to your project."]
Please update the "add-on" to "operator"

2023-03-15 16:24 UTC, ritz303 commented on controllers/reconcilers/quickstartinstallation/connecting-an-application-to-a-database-instance-using-the-topology-view-quick-start.yaml
> +  prerequisites: ["Access to the OpenShift console.", "Installation of the OpenShift Database Access add-on.", "A cloud-hosted database provider added to your project."]
@mrrajan : Good catch! Thanks for taking a look.

2023-03-22 14:31 UTC, tchughesiv requested changes
we may have to move away from using mongo as the example, depending on what they decide wrt merging our code upstream. maybe the safer route is to use RDS since we're more likely to package that with our release?

2023-03-22 16:45 UTC, tchughesiv requested changes
also, could you please remove any references you find around this being a "service preview" release... or beta release? thanks

2023-03-23 20:35 UTC, ritz303 commented on controllers/reconcilers/quickstartinstallation/installing-the-openshift-database-access-operator-quick-start.yaml
> +  prerequisites: ["OpenShift Container Platform 4.10 or higher.", "Running a OpenShift Dedicated, or an OpenShift Service on Amazon Web Services (AWS).", "AWS account and credentials."]
@tchughesiv : Thanks for the feedback!  I've updated the prereqs accordingly.

2023-03-24 17:30 UTC, tchughesiv commented on controllers/reconcilers/quickstartinstallation/installing-the-openshift-database-access-operator-quick-start.yaml
> +  prerequisites: ["Either OpenShift Container Platform or Origin Key Distribution (OKD) 4.10 or higher"]
Is that what OKD stands for? I always thought it was OpenShift Community Distribution

2023-03-28 16:35 UTC, tchughesiv requested changes
@ritz303 i think we'll need to remove mentions of mongodb atlas from the docs. let's use RDS as an example instead and in docs/references

also, please remove mentions of this release being "service preview". tks!

2023-03-28 17:52 UTC, ritz303 commented
@tchughesiv :  I thought I got all of the "Service Preview" instances, but I did find one more, so thank you for double checking me.  I've also replaced all mentions of MongoDB and replaced them with Amazon RDS.  Please let me know if I've missed anything.

2023-03-28 18:51 UTC, ritz303 commented
@tchughesiv : Thanks for taking a look!  I've removed the draft status.  I'm curious, can you do a squash on my commits before merging this PR into main?

2023-03-28 18:57 UTC, ritz303 reviewed
Finished reviewing the documentation.

2023-03-29 14:37 UTC, tchughesiv approved these changes

2023-03-29 14:37 UTC, merged