Cleanup Makefile
RHEcosystemAppEng/dbaas-operator pull request #367
Opened 2023-04-10 14:40 UTC by jianrongzhang89

## Description
Clean up the instructions on how to build and push the images.

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2023-04-10 15:59 UTC, tchughesiv requested changes

2023-04-10 15:59 UTC, tchughesiv commented on README.md
> -- **Next edit the [catalog-source.yaml](config/samples/catalog-source.yaml) template to indicate your new Quay.io org image**
This bit would have to stay in order for the rest to work.

2023-04-10 15:59 UTC, tchughesiv commented
Please thoroughly test whatever mods you make with this PR

2023-04-10 16:05 UTC, redhatHameed commented on README.md
> -- **Next edit the [catalog-source.yaml](config/samples/catalog-source.yaml) template to indicate your new Quay.io org image**
we can move this into ## `Building the Operator` section

2023-04-11 17:45 UTC, jianrongzhang89 commented on README.md
> -- **Next edit the [catalog-source.yaml](config/samples/catalog-source.yaml) template to indicate your new Quay.io org image**
Removed the manual edit step and cleaned this up.

2023-04-11 17:46 UTC, jianrongzhang89 commented
> Please thoroughly test whatever mods you make with this PR

Tested in.fresh cluster successfully.

2023-04-11 17:52 UTC, tchughesiv requested changes

2023-04-11 17:52 UTC, tchughesiv commented on config/samples/catalog-source-template.yaml
> +  image: {{CATALOG_IMG}}
Maybe we make this template a new file, and leave the original file in place?

2023-04-11 18:43 UTC, jianrongzhang89 commented on config/samples/catalog-source-template.yaml
> +  image: {{CATALOG_IMG}}
This is a new file. The original file is no longer needed so I think it should be removed.

2023-04-11 18:45 UTC, tchughesiv commented on config/samples/catalog-source-template.yaml
> +  image: {{CATALOG_IMG}}
IMO, it is still needed. I use it often on its own, without any make command.

2023-04-12 13:34 UTC, jianrongzhang89 commented on config/samples/catalog-source-template.yaml
> +  image: {{CATALOG_IMG}}
@tchughesiv sounds good. I added it back.

2023-04-12 13:53 UTC, tchughesiv requested changes

2023-04-12 15:13 UTC, jianrongzhang89 commented on Makefile
> +	sed "s/{{CATALOG_IMG}}/$(subst /,\/,$(CATALOG_IMG))/g" config/samples/catalog-source-template.yaml > config/samples/catalog-source.yaml
Yes, this file gets updated during catalog-build or catalog-update steps. This would be the same as other generated files (like the csv file) if one uses a different VERSION or ORG value. (if no custom ORG or VERSION is used, the file content would remain the same as the existing one.

2023-04-12 15:52 UTC, tchughesiv requested changes

2023-04-12 16:15 UTC, jianrongzhang89 commented on Makefile
> +	sed "s/{{CATALOG_IMG}}/$(subst /,\/,$(CATALOG_IMG))/g" config/samples/catalog-source-template.yaml > config/samples/catalog-source.yaml
ok

2023-04-12 16:15 UTC, jianrongzhang89 commented on Makefile
> +	sed "s/{{CATALOG_IMG}}/$(subst /,\/,$(CATALOG_IMG))/g" config/samples/catalog-source-template.yaml > config/samples/catalog-source.yaml
done

2023-04-12 16:21 UTC, tchughesiv requested changes

2023-04-12 16:21 UTC, tchughesiv commented on Makefile
> +	sed "s/{{CATALOG_IMG}}/$(subst /,\/,$(CATALOG_IMG))/g" config/samples/catalog-source-template.yaml > config/samples/catalog-source.yaml
please remove this new line as well...

2023-04-12 16:32 UTC, tchughesiv approved these changes
lgtm

2023-04-12 16:34 UTC, merged