DBAAS-175 Add validation logic to DBaaSInventory creation with webhook
RHEcosystemAppEng/dbaas-operator pull request #62
Opened 2021-10-12 13:25 UTC by jianrongzhang89

## Description
This PR is to add the validation logic for DBaaSInventory creation/update using a webhook along with CRD validation. The validation checks:
 -- if spec.providerRef.name is provided (by CRD validation)
 -- if spec.crednetialsRef.name is provided (by CRD validation). Spec.crednetialsRef.namespace can be optional and if it is empty, the default (CR's namespace) is used instead.
 -- check if the mandatory fields in the credendialsRef secret are present based on the provider.

Unit test is added. Tested successfully locally.

## Verification Steps
1) Download the attached zip file and extract to a local directory.
[test2.zip](https://github.com/RHEcosystemAppEng/dbaas-operator/files/7365438/test2.zip)
2) Log on to a cluster where DBaaS operator is installed and switch to openshift-dbaas-operator namespace.
3) oc apply -f dbassinventory-missing-provider-name.yaml
The DBaaSInventory "dbaas-jianrzha" is invalid: spec.providerRef: Required value
4) oc apply -f dbassinventory-missing-cred-name.yaml
The DBaaSInventory "dbaas-jianrzha" is invalid: spec.credentialsRef.name: Required value
5) create a secret: 
oc apply -f atlas-key-secret.yaml
secret/my-atlas-key created
5) Create a CR without credentialsRef.namespace. It should use the default namespace (from the CR).
oc apply -f dbassinventory-missing-cred-namespace.yaml
dbaasinventory.dbaas.redhat.com/dbaas-jianrzha created
(note that since dummy credentials are used here, you will see AuthenticationError error in the status, and this is expected).

6) Delete the CR for next test.
oc delete -f dbassinventory.yaml
'dbaasinventory.dbaas.redhat.com "dbaas-jianrzha" deleted

7) Create a secret where orgID is missing:
 oc apply -f  atlas-key-secret-missing-key.yaml 
8) Now creating a CR will cause validation error:
oc apply -f dbassinventory.yaml
Error from server (orgId is required in secret my-atlas-key): error when creating "dbassinventory.yaml": admission webhook "vdbaasinventory.kb.io" denied the request: orgId is required in secret my-atlas-key
9) Now apply a normal secret
oc apply -f atlas-key-secret.yaml
secret/my-atlas-key configured
10) Now we can create a CR successfully(note the secret includes dummy credentials data, so the status of the CR will show error and this is expected)
 oc apply -f dbassinventory.yaml
dbaasinventory.dbaas.redhat.com/dbaas-jianrzha created
11) We will try to test CR update cases.
  oc apply -f dbassinventory-missing-provider-name.yaml
The DBaaSInventory "dbaas-jianrzha" is invalid: spec.providerRef: Required value
jianrzha-mac:test zhangj$ oc apply -f dbassinventory-missing-cred-name.yaml
The DBaaSInventory "dbaas-jianrzha" is invalid: spec.credentialsRef.name: Required value

jianrzha-mac:test zhangj$ oc apply -f dbassinventory-missing-cred-namespace.yaml
dbaasinventory.dbaas.redhat.com/dbaas-jianrzha configured

jianrzha-mac:test zhangj$ oc delete secret/my-atlas-key
secret "my-atlas-key" deleted
jianrzha-mac:test zhangj$ oc apply -f atlas-key-secret-missing-key.yaml
secret/my-atlas-key created
jianrzha-mac:test zhangj$ oc apply -f  dbassinventory.yaml
Error from server (orgId is required in secret my-atlas-key): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"dbaas.redhat.com/v1alpha1\",\"kind\":\"DBaaSInventory\",\"metadata\":{\"annotations\":{},\"name\":\"dbaas-jianrzha\",\"namespace\":\"openshift-dbaas-operator\"},\"spec\":{\"credentialsRef\":{\"name\":\"my-atlas-key\",\"namespace\":\"openshift-dbaas-operator\"},\"providerRef\":{\"name\":\"mongodb-atlas-registration\"}}}\n"}},"spec":{"credentialsRef":{"namespace":"openshift-dbaas-operator"}}}
to:
Resource: "dbaas.redhat.com/v1alpha1, Resource=dbaasinventories", GroupVersionKind: "dbaas.redhat.com/v1alpha1, Kind=DBaaSInventory"
Name: "dbaas-jianrzha", Namespace: "openshift-dbaas-operator"
for: "dbassinventory.yaml": admission webhook "vdbaasinventory.kb.io" denied the request: orgId is required in secret my-atlas-key

## Type of change

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

An example of errors when creating a provider account without the required fields
![Screen Shot 2021-10-12 at 10 21 51 AM](https://user-images.githubusercontent.com/81316829/136974484-8ba012c4-e6f7-4104-9938-18d0d741cc26.png)
:

2021-10-13 16:07 UTC, fOO223Fr commented
I accidentally created the secret `atlas-key-secret-missing-key.yaml` in openshift-marketplace. which resulted in below error:
`$ oc apply -f dbassinventory.yaml
Error from server (NotFound): error when creating "dbassinventory.yaml": admission webhook "vdbaasinventory.kb.io" denied the request: secrets "my-atlas-key" not found
`
Is that the expected behavior?

Later when i create the said secret in `openshift-dbaas-operator` project then i got the desired output.

2021-10-13 17:21 UTC, jianrongzhang89 commented
> @jianrongzhang89 For verification step 10 below commands: oc apply -f dbassinventory-missing-provider-name.yaml oc apply -f dbassinventory-missing-cred-name.yaml oc apply -f dbassinventory-missing-cred-namespace.yaml had outputs along with the metadata. for example check below: `Error from server (spec.providerRef.name is required): error when applying patch:` **{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{"apiVersion":"dbaas.redhat.com/v1alpha1","kind":"DBaaSInventory","metadata":{"annotations":{},"name":"dbaas-jianrzha","namespace":"openshift-dbaas-operator"},"spec":{"credentialsRef":{"name":"my-atlas-key","namespace":"openshift-dbaas-operator"},"providerRef":{"name":""}}}\n"}},"spec":{"providerRef":{"name":""}}} to: Resource: "dbaas.redhat.com/v1alpha1, Resource=dbaasinventories", GroupVersionKind: "dbaas.redhat.com/v1alpha1, Kind=DBaaSInventory" Name: "dbaas-jianrzha", Namespace: "openshift-dbaas-operator"** `for: "dbassinventory-missing-provider-name.yaml": admission webhook "vdbaasinventory.kb.io" denied the request: spec.providerRef.name is required ` the above bold section is not pleasant.
> 
> Further in 10 after performing `oc delete secret/my-atlas-key` and `oc apply -f atlas-key-secret-missing-key.yaml` the output of `oc apply -f dbassinventory.yaml` was not as expected instead it was applied/configured/unchanged.

Yes this is fine. The key thing is the error message should appear:
 admission webhook "vdbaasinventory.kb.io" denied the request: spec.providerRef.name is required

2021-10-13 19:01 UTC, xieshenzh commented on api/v1alpha1/dbaasinventory_webhook.go
> +	}
I guess `Namespace` is optional, and we could use marker to mark the `Name` required instead.

2021-10-13 19:06 UTC, xieshenzh commented on api/v1alpha1/dbaasinventory_webhook.go
> +	secret, err := clientset.CoreV1().Secrets(inv.Spec.DBaaSInventorySpec.CredentialsRef.Namespace).Get(context.TODO(), inv.Spec.DBaaSInventorySpec.CredentialsRef.Name, metav1.GetOptions{})
Now that the client from `mgr.GetClient()` is usable in this context, maybe we could read the secrets with that client as well and no need to use `client-go`.

2021-10-18 13:13 UTC, jianrongzhang89 commented on controllers/dbaasinventory_controller.go
> +//+kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch
Good point. Done.

2021-10-18 13:14 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasinventory_webhook.go
> +	}
Yes this sounds good. I modified NamespacedName struct so that object Name is required but Namespace remains optional.

2021-10-18 15:06 UTC, xieshenzh commented on api/v1alpha1/dbaasinventory_webhook.go
> +var restClient client.Client = nil
```suggestion
var client client.Client = nil
```

2021-10-18 19:01 UTC, jianrongzhang89 commented on controllers/reconcilers/constants.go
>  	CRUNCHY_BRIDGE_CATLOG_IMG                = "registry.developers.crunchydata.com/crunchydata/crunchy-bridge-operator-catalog:v0.0.1"
Changed "CATLOG" to "CATALOG".

2021-10-18 19:02 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasinventory_webhook.go
> +var restClient client.Client = nil
Renamed restClient to apiClient

2021-10-19 17:47 UTC, xieshenzh commented on api/v1alpha1/dbaasinventory_webhook.go
> +				//return fmt.Errorf("%s", msg)
```suggestion
				return field.Invalid(field.NewPath("spec").Child("credentialsRef"), *(inv.Spec.CredentialsRef), msg)
```

This could be simplified.

2021-10-20 14:02 UTC, xieshenzh submitted a review, later dismissed

2021-11-23 18:22 UTC, tchughesiv requested changes

2021-11-23 18:22 UTC, tchughesiv commented on bundle/manifests/dbaas-operator.clusterserviceversion.yaml
> +          - watch
this seems like more perms than are needed for this feature, especially at a cluster-level. couldn't we limit the verbs to `get` instead? i worry about cluster-wide secret access via list and it doesn't appear we're watching secrets for changes with this PR.
```yaml
          verbs:
          - get
```

2021-11-24 15:51 UTC, jianrongzhang89 commented on bundle/manifests/dbaas-operator.clusterserviceversion.yaml
> +          - watch
Thanks @tchughesiv yes we only need "get". I updated the PR accordingly.

2021-12-06 19:19 UTC, tchughesiv commented on controllers/reconcilers/constants.go
> +	DBAAS_DYNAMIC_PLUGIN_IMG                 = "quay.io/ecosystem-appeng/dbaas-dynamic-plugin:0.1.2"
any reason we're going back a version here?

2021-12-06 19:19 UTC, tchughesiv commented on controllers/reconcilers/constants.go
> +	MONGODB_ATLAS_CATALOG_IMG                = "quay.io/ecosystem-appeng/mongodb-atlas-operator-catalog:0.7.2"
is this image change intentional? intended to release like this?

2022-01-18 16:47 UTC, tchughesiv requested changes

2022-01-18 16:47 UTC, tchughesiv commented on api/v1alpha1/dbaasinventory_webhook.go
> +//+kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch
please change to `//+kubebuilder:rbac:groups="",resources=secrets,verbs=get` if all you need are `get` perms

2022-01-18 16:47 UTC, tchughesiv commented on config/crd/bases/dbaas.redhat.com_dbaasinventories.yaml
> +                - name
how critical is this change? if critical, it needs to be persisted with kubebuilder. Was this added manually?
does this get overwritten if you run `make generate bundle`?
https://github.com/RHEcosystemAppEng/dbaas-operator/blob/2ce532dde6d052454ec3d56a4e9391974b09b579/api/v1alpha1/dbaastenant_types.go#L29

2022-01-18 18:12 UTC, jianrongzhang89 commented on config/crd/bases/dbaas.redhat.com_dbaasinventories.yaml
> +                - name
This is auto generated based on api/v1alpha1/dbaasprovider.go during the build.

2022-01-18 20:08 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasinventory_webhook.go
> +//+kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch
With "get" only, the validation would fail as:
2022-01-18T20:01:47.032Z	INFO	dbaasinventory-resource	validate create	{"name": "dbaas-jianrzha"}
E0118 20:02:01.705282       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:openshift-dbaas-operator:dbaas-operator-controller-manager" cannot list resource "secrets" in API group "" at the cluster scope

2022-01-18 22:03 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasinventory_webhook.go
> +//+kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch
Thank you @tchughesiv. I added secrets to ClientDisableCacheFor in the manager so that no cache is used when calling the API to get the secret. In this way, only "get" is needed.

2022-01-18 22:06 UTC, tchughesiv approved these changes
lgtm

2022-01-18 22:11 UTC, merged