DBAAS-203: reduce the permissions that the operator needs for platform reconciler
RHEcosystemAppEng/dbaas-operator pull request #64
Opened 2021-10-19 02:15 UTC by xieshenzh

## Description

Disable the uninstallation of the platform resources and reduce the permissions that the operator needs.

Jira: https://issues.redhat.com/browse/DBAAS-203

## Verification Steps

1. Install the dbaas operator
2. Check if the platform resources are installed in the same namespace as the dbaas operator
3. Uninstall the dbaas operator
4. Check if the namespace-scoped platform resources are all deleted
5. Re-install the dbaas operator 
6. Check if everything is up and running

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2021-10-19 05:15 UTC, bmozaffa commented
Thanks for this! Does this end up cleaning up via owner references, or does it, as I suggested, just not fully clean up to avoid the perms? If we face a choice between cleaning up and not having elevated permissions, we should probably go with the latter, but let's double check before making that decision. Relatedly, since OSD uses addons, does the addon uninstall not have the ability to clean up outside of our operator code?

2021-10-19 13:45 UTC, jianrongzhang89 commented on controllers/dbaasplatform_controller.go
> +			reconcilers.DBAAS_DYNAMIC_PLUGIN_NAME, r.InstallNamespace,
So here the plugins will be installed in the dbaas operator's namespace. Should the SBO and provider operators get installed in this namespace too?

2021-10-19 13:57 UTC, tchughesiv commented on controllers/dbaasplatform_controller.go
> +			reconcilers.DBAAS_DYNAMIC_PLUGIN_NAME, r.InstallNamespace,
I think, definitely the provider operators should be considered for this... but with SBO, why aren't we installing that as a csv dependency? aren't we using the official SBO operator?

2021-11-23 19:26 UTC, tchughesiv approved these changes
lgtm

2021-11-23 19:28 UTC, tchughesiv requested changes

2021-11-23 19:28 UTC, tchughesiv commented on controllers/dbaasplatform_controller.go
> +//+kubebuilder:rbac:groups=operators.coreos.com,resources=subscriptions;clusterserviceversions,verbs=get;list;create;update;watch;delete
do we still require `delete` perms for csv/subs? this seems unnecessary?

2021-11-23 19:59 UTC, xieshenzh commented on controllers/dbaasplatform_controller.go
> +//+kubebuilder:rbac:groups=operators.coreos.com,resources=subscriptions;clusterserviceversions,verbs=get;list;create;update;watch;delete
The owner references of the provider operators' subscriptions and csvs are set to be the dbaasplatform CR so that they will be deleted when uninstalling the dbaas operator (the owner reference of the dbaasplatform CR is the dbaas operator's csv).

It seems the [OwnerReferencesPermissionEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement) admission controller is enabled for openshift by default. Because I got this error when testing it:

> 2021-11-18T21:52:04.109Z	ERROR	controller-runtime.manager.controller.dbaasplatform	Reconciler error	{"reconciler group": "dbaas.redhat.com", "reconciler kind": "DBaaSPlatform", "name": "dbaas-platform", "namespace": "openshift-dbaas-operator", "error": "clusterserviceversions.operators.coreos.com \"service-binding-operator.v0.10.0\" is forbidden: cannot set an ownerRef on a resource you can't delete: , <nil>"}

So I kept the `delete` permission to set the owner references, and also added `update` permission for `clusterserviceversions/finalizers` for the same reason.

2021-11-23 20:38 UTC, tchughesiv commented on controllers/dbaasplatform_controller.go
> +//+kubebuilder:rbac:groups=operators.coreos.com,resources=subscriptions;clusterserviceversions,verbs=get;list;create;update;watch;delete
is that the route we decided to take here? to clean up other operator installs when dbaas is uninstalled? what about something like SBO?

2021-11-23 20:53 UTC, xieshenzh commented on controllers/dbaasplatform_controller.go
> +//+kubebuilder:rbac:groups=operators.coreos.com,resources=subscriptions;clusterserviceversions,verbs=get;list;create;update;watch;delete
We try to remove all the platform resources that the dbaas operator is supposed to create, including the subscription and csv of the service binding operator. Especially with this PR, everything is created in the same namespace.

The whole feature of dbaas platform was brought from the managed kafka project. I don't think we fully discussed it. 
Personally I think all the platform resources should be independent of the dbaas operator. All the provider operators and dynamic plugins should not be created by the dbaas operator. But for now, the dbaas operator creates all these things and deletes as many as possible.

2021-11-24 01:36 UTC, jianrongzhang89 commented on controllers/dbaasplatform_controller.go
> +//+kubebuilder:rbac:groups=operators.coreos.com,resources=subscriptions;clusterserviceversions,verbs=get;list;create;update;watch;delete
@xieshenzh could you document with comments in the code, or in readme file that when dbaas operator is removed by OLM, what will be deleted and what will be left?

2021-11-24 18:36 UTC, xieshenzh commented on controllers/dbaasplatform_controller.go
> +//+kubebuilder:rbac:groups=operators.coreos.com,resources=subscriptions;clusterserviceversions,verbs=get;list;create;update;watch;delete
@jianrongzhang89 documented with comments in the code: https://github.com/RHEcosystemAppEng/dbaas-operator/blob/5665e3efc2bfde909dbe299b4a2640aa4fd61f54/controllers/dbaasplatform_controller.go#L45-L65

2021-12-06 19:09 UTC, tchughesiv reviewed
added a question about UI & provider updates in future releases... otherwise lgt

2021-12-06 19:09 UTC, tchughesiv commented on controllers/dbaasplatform_controller.go
> +//+kubebuilder:rbac:groups=operators.coreos.com,resources=subscriptions;clusterserviceversions,verbs=get;list;create;update;watch;delete
i see `Platform resources NOT to be removed or updated by the DBaaS operator`... so how do we handle updates to those components when necessary?

2021-12-06 19:14 UTC, tchughesiv submitted a review, later dismissed

2021-12-07 16:24 UTC, xieshenzh commented on controllers/dbaasplatform_controller.go
> +//+kubebuilder:rbac:groups=operators.coreos.com,resources=subscriptions;clusterserviceversions,verbs=get;list;create;update;watch;delete
They will be updated, for example: https://github.com/RHEcosystemAppEng/dbaas-operator/blob/5665e3efc2bfde909dbe299b4a2640aa4fd61f54/controllers/reconcilers/console_plugin/plugin_installation_reconciler.go#L242

But we might not be able to support the upgrade for future releases, if we have to install these resources in a different way, for example using operators.

2021-12-07 18:59 UTC, jianrongzhang89 approved these changes

2021-12-16 14:29 UTC, merged