DBaaS-204: create new CRD and controller for provisioning
RHEcosystemAppEng/dbaas-operator pull request #71
Opened 2021-11-22 16:10 UTC by xieshenzh

Jira: https://issues.redhat.com/browse/DBAAS-204

## Description

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2022-01-07 15:26 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	DBaaSInstanceProviderSyncType   string = "SpecSynced"
SpecSynced => ProvisionReady

2022-01-07 17:14 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Provider string `json:"provider"`
=>CloudProvider

2022-01-07 17:14 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	Region string `json:"region"`
=>CloudRegion

2022-01-14 15:17 UTC, redhatHameed reviewed
@xieshenzh LGTM is there anything remaining to work on this PR?

2022-01-14 15:19 UTC, xieshenzh commented
> @xieshenzh LGTM is there anything remaining to work on this PR?

I am not sure if the design is finalized.

2022-01-18 22:54 UTC, tchughesiv requested changes
please rebase

2022-01-19 14:44 UTC, tchughesiv commented on controllers/dbaasinstance_controller.go
> +//+kubebuilder:rbac:groups=dbaas.redhat.com,resources=dbaasinstances/finalizers,verbs=update
i think we've been using resource wildcards for the other CRDs. I'm ok moving away from wildcards towards this but i think we should chose one way to do it. Either we define rbac for each dbaas resource type, or we use wildcards that account for all of them. thoughts?
https://github.com/RHEcosystemAppEng/dbaas-operator/blob/c4ca7029848e7fcb0191f1c0e1755b798109a996/controllers/dbaasinventory_controller.go#L36-L38

2022-01-19 14:44 UTC, tchughesiv commented on api/v1alpha1/dbaasprovider.go
> +	AllowsFreeTrial bool `json:"allowsFreeTrial"`
should this be an optional bool instead and, if not set, we assume `false`?

2022-01-19 14:44 UTC, tchughesiv commented on api/v1alpha1/dbaasprovider.go
> +	ProvisionURL string `json:"provisionUrl"`
should this be optional?

2022-01-19 14:44 UTC, tchughesiv commented on api/v1alpha1/dbaasprovider.go
> +	ProvisionInstructions string `json:"provisionInstructions"`
should this be optional?

2022-01-19 14:44 UTC, tchughesiv commented on api/v1alpha1/dbaasprovider.go
> +	InstanceParameterSpecs []InstanceParameterSpec `json:"instanceParameterSpecs"`
should this be optional?

2022-01-19 15:22 UTC, xieshenzh commented on api/v1alpha1/dbaasprovider.go
> +	AllowsFreeTrial bool `json:"allowsFreeTrial"`
This is from the ADR. I think it is better to discuss in the ADR.

2022-01-19 18:17 UTC, tchughesiv approved these changes
lgtm

2022-01-19 18:20 UTC, merged