[WIP] DBAAS-201 DBaaS Operator error handling enhancements
RHEcosystemAppEng/dbaas-operator pull request #72
Opened 2021-11-23 19:05 UTC by jianrongzhang89

## Description

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2021-11-30 14:38 UTC, redhatHameed reviewed
Thanks added a few comments

2021-11-30 14:38 UTC, redhatHameed commented on api/v1alpha1/dbaasprovider.go
> +const (
can make one const var? and add the comments for each section

2021-11-30 14:38 UTC, redhatHameed commented on controllers/dbaasconnection_controller.go
> +func SetConnectionCondition(conn *v1alpha1.DBaaSConnection, condType string, status metav1.ConditionStatus, reason, msg string) {
is it possible to use a builtin function from ->  k8s.io/apimachinery/pkg/apis/meta/v1 https://github.com/kubernetes/apimachinery/blob/master/pkg/api/meta/conditions.go#L30
done in crunchy bridge operator 
https://github.com/CrunchyData/crunchy-bridge-operator/blob/master/controllers/dbaas.redhat.com/conditions.go#L44

2021-11-30 14:38 UTC, redhatHameed commented on controllers/dbaasplatform_controller.go
>  		dbaasv1alpha1.ServiceBindingInstallation,
+1 changing the order of platform installation plugin first then providers operators

2021-11-30 14:51 UTC, tchughesiv requested changes

2021-11-30 14:51 UTC, tchughesiv commented on controllers/dbaasinventory_controller.go
> +		return ctrl.Result{}, fmt.Errorf(v1alpha1.DBaaSTenantNotFound)
not sure we want to throw errors during inventory reconcile for every inventory that doesn't reside in a tenant namespace. this could be a common occurrence in certain clusters and isn't necessarily something to be concerned about.

If we think we want to display this, should it instead be a debug message? warning?

2021-11-30 14:51 UTC, tchughesiv commented on controllers/dbaasinventory_controller.go
> +	}(&inventory)
This PR has to do with error handling, bit these are significant changes likely to negatively impact reconcile flow. This block of code should stay where it was. The reason is that we don't want to even attempt a reconciliation of an inventory unless it exists in a "tenant namespace". We should just ignore all other inventories in the cluster.

2021-11-30 15:56 UTC, tchughesiv commented on controllers/dbaasinventory_controller.go
> +	}(&inventory)
looking at this closer, i agree it makes sense... as long as we remove the below error.

2021-11-30 16:08 UTC, jianrongzhang89 commented on controllers/dbaasinventory_controller.go
> +		return ctrl.Result{}, fmt.Errorf(v1alpha1.DBaaSTenantNotFound)
Yes, you are right. They are not really errors and will clog the pod logs. I think changing to debug is good.

@jeremyary @xieshenzh @redhatHameed do you think debug message is good here, or should a warning be logged instead?

2021-11-30 16:10 UTC, jianrongzhang89 commented on controllers/dbaasconnection_controller.go
> +func SetConnectionCondition(conn *v1alpha1.DBaaSConnection, condType string, status metav1.ConditionStatus, reason, msg string) {
Yes this is a good idea. I changed to use the standard function call for both setcondition and getcondition calls and upated the PR.

2021-11-30 19:23 UTC, xieshenzh commented on controllers/dbaasconnection_controller.go
>  	if err := r.reconcileDBaaSObjectStatus(&connection, func() error {
Since the status is updated in the deferred function, it is not necessary to update it here.
You may use the function `reconcileDBaaSObjectStatus` as the deferred function, or delete it because it is not used anywhere else.
And make sure check if the err is `Conflict`, we don't have to write `Conflict` error in the logs.

2021-12-01 16:04 UTC, redhatHameed commented on controllers/dbaasinventory_controller.go
> +		return ctrl.Result{}, fmt.Errorf(v1alpha1.DBaaSTenantNotFound)
How about adding the info message? if not then you can make it debug.

2021-12-01 16:41 UTC, jianrongzhang89 commented on controllers/dbaasconnection_controller.go
>  	if err := r.reconcileDBaaSObjectStatus(&connection, func() error {
Thanks @xieshenzh, yes this can be simplified. I removed reconcileDBaaSObjectStatus all together and updated the PR accordingly.

2021-12-01 16:43 UTC, jianrongzhang89 commented on controllers/dbaasinventory_controller.go
> +		return ctrl.Result{}, fmt.Errorf(v1alpha1.DBaaSTenantNotFound)
I used logger.V(1).Info() for this message.

2021-12-02 21:23 UTC, redhatHameed commented on api/v1alpha1/dbaasprovider.go
> +	DBaaSInventoryReadyType         string = "Ready"
@jianrongzhang89 why we need `Type: Ready` I mean why not use the same type `ReadyForBinding`or `SpecSynced`

2021-12-02 21:52 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	DBaaSInventoryReadyType         string = "Ready"
@redhatHameed we need to use a different condition type to separate dbaas specific condition from ReadyForBinding or SpecSynced which is copied from provider provider operator CRs.

2021-12-02 23:19 UTC, tchughesiv submitted a review, later dismissed

2021-12-03 16:13 UTC, xieshenzh requested changes

2021-12-03 16:13 UTC, xieshenzh commented on controllers/dbaasinventory_controller.go
> +		status.Conditions = append(status.Conditions, *cond)
It seems the condition with type `v1alpha1.DBaaSInventoryReadyType` will always be reset at line 240 or 244. In this case, it doesn't make sense to set it here.

2021-12-03 16:31 UTC, redhatHameed commented on api/v1alpha1/dbaasprovider.go
> +	DBaaSInventoryReadyType         string = "Ready"
can we change the name of type from 'Ready' to 'ReconcileSuccess' WDYT?

2021-12-03 19:14 UTC, jianrongzhang89 commented on controllers/dbaasconnection_controller.go
> +			setConnectionCondition(&connection, v1alpha1.DBaaSConnectionReadyType, metav1.ConditionFalse, v1alpha1.ProviderReconcileInprogress, "DBaaS Provider Custom Resource created or updated")
Sounds good. Done

2021-12-06 02:56 UTC, jianrongzhang89 commented on controllers/dbaasconnection_controller.go
> +	msg := "DBaaS Provider Custom Resource reconcilation in progress"
Corrected and defined as a const.

2021-12-06 02:58 UTC, jianrongzhang89 commented on controllers/dbaasconnection_controller.go
> +}
The set function is a useful help function so I kept it but  I combined the setConnectionCondition and setInventoryCOndition into one and moved it to api package. The getConnectionCondition is replaced with apimeta function calls directly.

2021-12-06 03:00 UTC, jianrongzhang89 commented on controllers/dbaasinventory_controller.go
> +func mergeInventoryStatus(inv *v1alpha1.DBaaSInventory, providerInv *v1alpha1.DBaaSProviderInventory) error {
Actually, because DBaaSInventoryStatus and DBaaSConnectionStatus are two different data structures, mergeInventoryStatus and mergeConnectionStatus can not be easily refactored into one so I prefer to keep them separate.

2021-12-06 03:02 UTC, jianrongzhang89 commented on controllers/dbaasinventory_controller.go
> +		status.Conditions = append(status.Conditions, *cond)
Actually, only the status, reason and msg are reset again later,  lastTransitionTime does not always gets reset depending on the specific values.

2021-12-06 03:07 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	DBaaSInventoryReadyType         string = "Ready"
This could change.  My preference is the short version of "Ready" though. @tchughesiv @xieshenzh and @jeremyary what do you think?

2021-12-06 04:37 UTC, xieshenzh commented on controllers/dbaasinventory_controller.go
> +		status.Conditions = append(status.Conditions, *cond)
If the condition is never used (i.e. its status, reason and msg will always be reset), I don't think there is any significance of its old value of lastTransitionTime. 
And it seems any condition of type `v1alpha1.DBaaSInventoryReadyType` is created by this controller, so I don't think it is a problem if this controller sets lastTransitionTime again in this function.

2021-12-06 04:56 UTC, xieshenzh commented on controllers/dbaasinventory_controller.go
> +		status.Conditions = append(status.Conditions, *cond)
Actually, I don't think the `Reconcile` function should set any condition of type `v1alpha1.DBaaSInventoryReadyType` unless it returns with requeue or error. Because the value will never be used, it will always be reset in this function.
On the other hand, if the `Reconcile` function doesn't set any condition of type `v1alpha1.DBaaSInventoryReadyType`, there is no need to read it in this function.

2021-12-06 05:00 UTC, xieshenzh commented on controllers/dbaasinventory_controller.go
> +	return fmt.Errorf(v1alpha1.MsgProviderCRReconcileInProgress)
This function should not return error here. `ProviderCRReconcileInProgress` is not an error. We don't have to requeue the Reconcile either. Once the provider finishes reconcile, it should update the provider CR which will trigger this Reconcile.

2021-12-06 19:18 UTC, jianrongzhang89 commented on controllers/dbaasinventory_controller.go
> +	return fmt.Errorf(v1alpha1.MsgProviderCRReconcileInProgress)
Agreed. Code updated.

2021-12-06 19:19 UTC, jianrongzhang89 commented on controllers/dbaasinventory_controller.go
> +		status.Conditions = append(status.Conditions, *cond)
@xieshenzh thank you very much for your suggestions! Based on our discussions, I simplified the code. Please review again.

2021-12-06 21:42 UTC, xieshenzh commented on controllers/dbaasconnection_controller.go
> +		if err != nil {
I think we can check if the error `IsConflict` here. `Reconcile` should be requeued if there is conflict when updating the status of the CR.
And we should alter the return values of function `Reconcile`, if we want to requeue or there is other error for updating the status of the CR.

2021-12-06 21:45 UTC, xieshenzh commented on controllers/dbaasconnection_controller.go
>  		logger.Error(err, "Error fetching DBaaS Inventory resource reference for DBaaS Connection", "DBaaS Inventory", connection.Spec.InventoryRef)
Should we also update the `DBaaSInventoryReadyType` condition for other errors like the one in this line? 
I am just curious why the condition is only updated for some of the error cases.

2021-12-07 01:37 UTC, jianrongzhang89 commented on controllers/dbaasconnection_controller.go
> +		if err != nil {
Agreed. Code updated to use named return values.

2021-12-07 01:40 UTC, jianrongzhang89 commented on controllers/dbaasconnection_controller.go
>  		logger.Error(err, "Error fetching DBaaS Inventory resource reference for DBaaS Connection", "DBaaS Inventory", connection.Spec.InventoryRef)
This intentional. I tried to separate the "business logic" errors (for instance tenant not found) from temporary errors (such us errors in retrieving an object from k8s) and the latter can normally get resolved through future reconciliations.

2021-12-07 16:05 UTC, xieshenzh commented on controllers/dbaasconnection_controller.go
> +		if err != nil {
Thanks. In the case that there are already errors or requeue request before updating the status, I don't think we should overwrite the errors or requeue request with the ones caused by updating status.
So I suggest we check if the return values are already set before altering the return values, when there is error for updating the status.

2021-12-07 17:09 UTC, jianrongzhang89 commented on controllers/dbaasconnection_controller.go
> +		if err != nil {
Thanks! I updated the code as we discussed.

2021-12-07 18:30 UTC, xieshenzh submitted a review, later dismissed

2021-12-15 19:11 UTC, redhatHameed commented on api/v1alpha1/dbaasprovider.go
> +	DBaaSInventoryReadyType         string = "Ready"
@jianrongzhang89 do we need this change. ? or want to keep 'Ready'

2021-12-16 14:31 UTC, jeremyary commented
@jianrongzhang89 can we clean up conflicts here, please? After that, I'll get it merged up. Thanks!!

2021-12-16 17:42 UTC, jeremyary commented
no-op comment, bumping to trigger actions

2021-12-16 18:13 UTC, jianrongzhang89 commented on api/v1alpha1/dbaasprovider.go
> +	DBaaSInventoryReadyType         string = "Ready"
@redhatHameed yes. Changed to "InventoryReady" and "ConnectionReady".

2021-12-16 18:44 UTC, jianrongzhang89 commented
> @jianrongzhang89 can we clean up conflicts here, please? After that, I'll get it merged up. Thanks!!

@jeremyary @tchughesiv The PR is rebased and all conflicts resolved. I retested and all cases passed.

2021-12-16 18:46 UTC, redhatHameed submitted a review, later dismissed

2021-12-16 19:11 UTC, tchughesiv requested changes

2021-12-16 19:11 UTC, tchughesiv commented on controllers/dbaasinventory_controller.go
> +		result, recErr = ctrl.Result{Requeue: true}, nil
why Requeue here?

2021-12-16 19:28 UTC, jianrongzhang89 commented on controllers/dbaasinventory_controller.go
> +		result, recErr = ctrl.Result{Requeue: true}, nil
This is required so that the inventory gets reconciled again when the user adds a tenant.

2021-12-16 19:36 UTC, tchughesiv commented on controllers/dbaasinventory_controller.go
> +		result, recErr = ctrl.Result{Requeue: true}, nil
won't this cause an infinite loop though, if no tenant for that namespace exists? i believe the requeue is initiated immediately.

2021-12-16 19:42 UTC, jianrongzhang89 commented on controllers/dbaasinventory_controller.go
> +		result, recErr = ctrl.Result{Requeue: true}, nil
You are right. It should not be requeued then. I just updated the PR.

2021-12-16 20:05 UTC, tchughesiv approved these changes

2021-12-16 20:05 UTC, tchughesiv commented
lgtm

2021-12-16 21:20 UTC, jeremyary approved these changes

2021-12-16 21:20 UTC, merged