Fix memory issue when setting owner references to CSVs
RHEcosystemAppEng/dbaas-operator pull request #90
Opened 2021-12-23 20:31 UTC by xieshenzh

## Description

For the cluster-scoped operators, every namespace has a copy of the CSVs.

So when running load test with thousands of namespaces, setting owner references to the CSVs of mongodb atlas operator, crunchy bridge operator and service binding operator will cause the dbaas operator to load the thousands copies of CSVs to the cache, as a result the memory limit is exceeded.

The solution is to bypass the cache and read the CSVs directly from the API server.

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2021-12-23 20:32 UTC, xieshenzh commented
Fix for https://github.com/RHEcosystemAppEng/dbaas-operator/pull/84

2021-12-23 21:08 UTC, tchughesiv commented
do we know what the impact to the stability of the api server would be with a change like this? how often are these calls made?

2021-12-23 21:47 UTC, xieshenzh commented
> do we know what the impact to the stability of the api server would be with a change like this? how often are these calls made?

I could reproduce the memory issue by simply installing the dbaas operator. There is no stability impact by only installing the dbaas operator based on my observation. 
If we want to create thousands of namespaces at the same time, the impact of creating the namespaces and other objects is definitely much more significant than this. We will have to run load test to figure out the difference.

At most three separate calls are made to read a CSV by its name and namespace for reconciling the dbaasplatform CR once. 
There is only one instance of the dbaasplatform CR, and the reconciling takes place most often during the startup of the operator to install the platform resources, around three times or less in every one second in my test. So there could be around ten calls to the api server made in every one second.

2022-01-04 16:46 UTC, tchughesiv requested changes

2022-01-04 16:46 UTC, tchughesiv commented on bundle/manifests/dbaas-operator.clusterserviceversion.yaml
> +          - delete
do we need create or delete perms for csv's? maybe split out csv perms to only what we need?

2022-01-04 16:46 UTC, tchughesiv commented on controllers/dbaasplatform_controller.go
> +func (r *DBaaSPlatformReconciler) getCleanupPlatforms() []dbaasv1alpha1.PlatformsName {
is this function still necessary if just returning `nil`?

2022-01-04 17:01 UTC, tchughesiv requested changes

2022-01-04 17:01 UTC, tchughesiv commented on controllers/reconcilers/csv/csv_reconciler.go
>  func GetDBaaSOperatorCSV(namespace string, ctx context.Context, serverClient k8sclient.Client) (*v1alpha1.ClusterServiceVersion, error) {
in this function, you're still doing a list of the csv's... which would force a cache of the csv's anyway. if bypassing cache for `get`, we should also do so for a csv `list`.

2022-01-04 17:05 UTC, tchughesiv commented on controllers/dbaas_reconciler.go
> +	client.Reader
if, with this change, we're only ever retrieving CSV's from the install namespace... the memory footprint for said csv's should be minimal. Are we sure we need to bypass cache for a single namespace worth of csv's?

2022-01-04 17:12 UTC, xieshenzh commented on controllers/reconcilers/csv/csv_reconciler.go
>  func GetDBaaSOperatorCSV(namespace string, ctx context.Context, serverClient k8sclient.Client) (*v1alpha1.ClusterServiceVersion, error) {
The `serverClient` doesn't use cache: https://github.com/RHEcosystemAppEng/dbaas-operator/blob/beb6d1e43f265bff9d38dc0c09ee63335b72bfb6/controllers/dbaasplatform_controller.go#L172

The code is executed before the controller starts.

2022-01-04 17:28 UTC, xieshenzh commented on controllers/dbaas_reconciler.go
> +	client.Reader
It seems it only supports restricting the manager's cache to watch all the namespace-scoped objects in the desired namespace, and we cannot do it only for csv: https://github.com/kubernetes-sigs/controller-runtime/blob/e52a8b1fba620f42bf6be7c6904c77a6da342898/pkg/manager/manager.go#L189-L195

2022-01-04 17:52 UTC, xieshenzh commented on controllers/dbaas_reconciler.go
> +	client.Reader
The operator only reads the csv when installing the platform resources. It is not supposed to happen very often.

2022-01-04 19:11 UTC, tchughesiv commented on controllers/dbaas_reconciler.go
> +	client.Reader
but we aren't watching csv's... only retrieving certain ones. right? seems odd it would still try to cache ALL csv's cluster-wide.

2022-01-04 20:25 UTC, xieshenzh commented on controllers/dbaas_reconciler.go
> +	client.Reader
You are right, and the 'namespace' settings are not actually for the client. 
But the default cache uses informers as well, which consumes resources: https://github.com/kubernetes-sigs/controller-runtime/blob/e52a8b1fba620f42bf6be7c6904c77a6da342898/pkg/cache/cache.go#L150

There is an option to bypass cache for all csv: https://github.com/kubernetes-sigs/controller-runtime/blob/e52a8b1fba620f42bf6be7c6904c77a6da342898/pkg/cluster/cluster.go#L119
We can use this option if we want to always bypass the cache when reading csv. For now, we only read csv when setting ownerreferences.

2022-01-04 22:00 UTC, tchughesiv commented on controllers/dbaas_reconciler.go
> +	client.Reader
I guess we should explore both? first, let's make sure moving to the "reader" interface has a significant impact memory usage at scale. second, test the cache disable option and see if that's a better alternative... might be a better way to go?

2022-01-04 22:03 UTC, tchughesiv commented on controllers/dbaas_reconciler.go
> +	client.Reader
might gut tells me `ClientDisableCacheFor` is the way to go here. simpler and ensures cache is bypassed.

2022-01-05 15:59 UTC, jianrongzhang89 commented on controllers/dbaasplatform_controller.go
> +		} else if err := ctrl.SetControllerReference(owner, cr, r.Scheme); err != nil {
Here "else if" can be replaced with if to make the code easier to understand.

2022-01-05 20:56 UTC, tchughesiv requested changes

2022-01-05 20:56 UTC, tchughesiv commented on bundle/manifests/dbaas-operator.clusterserviceversion.yaml
> +          - delete
seems `create` verb was removed, but not `delete`

2022-01-05 22:00 UTC, xieshenzh commented
DBaaS operator pod resource metrics for load test  with 2000 users, projects and tenants.
It does take very long time to install the platform resources (i.e. operators), though.
![Screenshot from 2022-01-05 16-43-44](https://user-images.githubusercontent.com/42279951/148295511-09853d1c-ada9-47d0-8d80-8452d59e7b86.png)

2022-01-05 22:00 UTC, xieshenzh commented on controllers/dbaasplatform_controller.go
> +		} else if err := ctrl.SetControllerReference(owner, cr, r.Scheme); err != nil {
done

2022-01-05 22:00 UTC, xieshenzh commented on controllers/dbaas_reconciler.go
> +	client.Reader
done

2022-01-06 15:59 UTC, tchughesiv approved these changes

2022-01-06 16:00 UTC, merged