fix binding permission issue, by installing binding operator in openshift-operators namespace
RHEcosystemAppEng/dbaas-operator pull request #96
Opened 2022-01-13 21:56 UTC by redhatHameed

## Description
issue :
https://issues.redhat.com/browse/DBAAS-255 

Fix the SBO permission, by installing SBO in the namespace `openshift-operators`
upgrade SBO version with latest/stable
update SBO labels as per the latest operator version guideline. 

## Verification Steps

1. Create DBaaS connection
2. Install sample application for Crunchy or MongoDB based on the connection provider type.
3. Connect the application with connection from topology view
4. Check if the application successfully connected with the selected database.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2022-01-14 15:11 UTC, redhatHameed commented
@jeremyary @xieshenzh @tchughesiv can you please take a look at this PR, once get time thanks

2022-01-14 15:20 UTC, tchughesiv requested changes

2022-01-14 15:20 UTC, tchughesiv commented on controllers/reconcilers/servicebinding/servicebinding_reconciler.go
>  func (r *Reconciler) getServiceBindingCSV(cr *v1.DBaaSPlatform) *v1alpha1.ClusterServiceVersion {
we can no longer assume we're the only ones using a specific install of service binding in a cluster. given this, is this function still necessary at all? it appears to only be used to delete the csv. Similarly, the function it's used in, `func (r *Reconciler) Cleanup` should no longer be necessary.

2022-01-14 15:34 UTC, redhatHameed commented on controllers/reconcilers/servicebinding/servicebinding_reconciler.go
>  func (r *Reconciler) getServiceBindingCSV(cr *v1.DBaaSPlatform) *v1alpha1.ClusterServiceVersion {
agreed and it's not used anymore removed the getServiceBindingCSV and cleanup logic from `func (r *Reconciler) Cleanup`. Keep the empty function signature as its implementing the [PlatformReconciler](https://github.com/RHEcosystemAppEng/dbaas-operator/blob/793e507b429eddf482d5efa3f18a522275fc3b2e/controllers/reconcilers/reconciler.go)

2022-01-14 16:20 UTC, xieshenzh submitted a review, later dismissed

2022-01-14 16:48 UTC, redhatHameed commented
> has this deployment been tested in an env where servicebinding is already installed. what about in an env where the wrong version is installed? i'm not sure we can/should change the version that a cluster's using in that case. some things to consider here.

The current operator behaves like, if there is an already installed version for example version v.0.1.0 the DBaaS operator will not be able to install the latest version but I see some errors in OLM like

"level":"error","ts":1642177972.2787035,"logger":"controllers.operatorcondition-generator","msg":"Unable to find ClusterServiceVersion","request":"openshift-dbaas-operator/service-binding-operator.v1.0.0","error":"ClusterServiceVersion.operators.coreos.com \"service-binding-operator.v1.0.0\" not 

but there is one issue we need to handle related with labels settings, we have different labels of permission to set according to the SBO version 
for example if the version v.0.1.0 the label is service.binding/controller: "true" in v.0.11 onwards the label is :     servicebinding.io/controller: "true" can we set both labels?

2022-01-14 16:57 UTC, tchughesiv commented
@redhatHameed if we move towards OLM dependencies declaration, this is no longer and issue we have to solve.

2022-01-14 17:02 UTC, redhatHameed commented
> if we're moving toward the official service binding operator, it feels like we should also switch to using the official dependency feature of olm. based on my limited understanding, a new dependencies.yaml file would be added to our bundle with something like the following:
> 
> ```yaml
> dependencies:
>   - type: olm.package
>     value:
>       packageName: service-binding-operator
>       version: ">=v0.10.0"
> ```
> 
> This would take care of everything for us ... installs, upgrades, etc. The `servicebinding_reconciler.go` code could then be removed. thoughts?
> 
> https://github.com/operator-framework/operator-registry/blob/master/docs/design/operator-bundle.md#bundle-dependencies https://olm.operatorframework.io/docs/concepts/olm-architecture/dependency-resolution/

@jeremyary your thoughts on this moving SBO operator installation using olm dependency

2022-01-14 17:06 UTC, redhatHameed commented
> @redhatHameed if we move towards OLM dependencies declaration, this is no longer an issue we have to solve.

Sounds good to me, but I think we still need to define the labels inside [dbaasconnection_viewer_role](https://github.com/RHEcosystemAppEng/dbaas-operator/blob/1c3cf8d137421632eb87e5da6356cc5dd701f24a/config/rbac/dbaasconnection_viewer_role.yaml#L7) based on the SBO version installed. We can define the two labels so should not be an issue

2022-01-14 19:26 UTC, jeremyary commented
@redhatHameed @tchughesiv I'm ok w/it, let's go for it. Some day, we hope they're all [trusted enough to be olm deps](https://gitlab.cee.redhat.com/service/managed-tenants/-/blob/main/docs/tenants/addons_dependencies.md#trusted-catalogs-list) :) To back up Tommy here, we should thoroughly test this in a fresh cluster, also in an SBO older version update cluster, etc. to make sure we're ok in scenarios we may encounter.

2022-01-17 06:54 UTC, redhatHameed commented
@tchughesiv @jeremyary 

OLM dependency will not work in our case. Because it installed SBO into RHODA/DBaaS installed namespace and we will face the same permission issue. The SBO only works properly into `openshift-operators` namespace.

2022-01-18 17:39 UTC, tchughesiv commented on bundle/manifests/dbaas-operator-dbaasconnection-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
>      service.binding/controller: "true"
can we remove this label? deprecated?

2022-01-18 17:44 UTC, redhatHameed commented on bundle/manifests/dbaas-operator-dbaasconnection-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
>      service.binding/controller: "true"
we can remove that if we stick with version >=1.0.0

2022-01-18 17:46 UTC, redhatHameed commented on bundle/manifests/dbaas-operator-dbaasconnection-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
>      service.binding/controller: "true"
I think we need the version >=1.0.0 because there is another issue we have seen for using deploymentconfig kind, which is not supported in version 0.10.0 
cc: @jeremyary

2022-01-18 19:01 UTC, tchughesiv requested changes
lgtm, just rebase and we can merge

2022-01-18 19:10 UTC, redhatHameed commented
> lgtm, just rebase and we can merge

Done.

2022-01-18 19:15 UTC, tchughesiv commented on controllers/reconcilers/constants.go
> +
appears you may need to run a `make fmt` and commit changes... one of the checks is failing.

2022-01-18 19:26 UTC, tchughesiv approved these changes
lgtm

2022-01-18 19:26 UTC, merged