[WIP] Add cockroachdb cloud operator to dbaas platform
RHEcosystemAppEng/dbaas-operator pull request #97
Opened 2022-01-14 18:13 UTC by myeung18

## Description

## Verification Steps

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

2022-01-17 07:04 UTC, redhatHameed commented on controllers/reconcilers/cockroachdb_intallation/cockroachdb_installation_reconciler.go
> +			Package:                "ccapi-k8s-operator",
can we some mean the full name of package like `corckraochdb-operator`

2022-01-17 07:04 UTC, redhatHameed commented on controllers/reconcilers/cockroachdb_intallation/cockroachdb_installation_reconciler.go
> +			Name:      "ccapi-k8s-subscription",
also here will be good if we give complete name : ccapi-k8s like `cockraochdb`

2022-01-17 07:04 UTC, redhatHameed commented on controllers/reconcilers/cockroachdb_intallation/cockroachdb_installation_reconciler.go
> +			Name:      "ccapi-k8s-catalogsource",
same complete name to better understand for catalogsource

2022-01-18 22:55 UTC, tchughesiv requested changes
please rebase

2022-01-19 16:33 UTC, jeremyary commented on controllers/reconcilers/constants.go
> +	DBAAS_DYNAMIC_PLUGIN_IMG                 = "quay.io/myeung/dbaas-dynamic-plugin:0.1.3"
this shouldn't be checked in

2022-01-19 16:35 UTC, jeremyary requested changes
added a few comments to clean up, nothing major. Thanks!

2022-01-20 13:18 UTC, myeung18 commented on controllers/reconcilers/cockroachdb_intallation/cockroachdb_installation_reconciler.go
> +			Package:                "ccapi-k8s-operator",
the name is official, we will stick to it.

2022-01-20 13:18 UTC, myeung18 commented on controllers/reconcilers/cockroachdb_intallation/cockroachdb_installation_reconciler.go
> +			Name:      "ccapi-k8s-catalogsource",
ditto

2022-01-20 13:18 UTC, myeung18 commented on controllers/reconcilers/cockroachdb_intallation/cockroachdb_installation_reconciler.go
> +			Name:      "ccapi-k8s-subscription",
ditto

2022-01-20 13:59 UTC, jeremyary reviewed
lgtm, I'll let you guys weigh in before we throw approval on it

2022-01-20 16:41 UTC, redhatHameed approved these changes

2022-01-20 18:13 UTC, xieshenzh approved these changes

2022-01-20 18:13 UTC, xieshenzh commented on controllers/reconcilers/cockroachdb_installation/cockroachdb_installation_reconciler.go
> +var _ reconcilers.PlatformReconciler = &Reconciler{}
```suggestion
```

2022-01-24 13:56 UTC, myeung18 commented on controllers/reconcilers/cockroachdb_installation/cockroachdb_installation_reconciler.go
> +var _ reconcilers.PlatformReconciler = &Reconciler{}
what do you mean, @xieshenzh 
This line stays.

2022-01-24 14:29 UTC, xieshenzh commented on controllers/reconcilers/cockroachdb_installation/cockroachdb_installation_reconciler.go
> +var _ reconcilers.PlatformReconciler = &Reconciler{}
I don't see any reason why this line should be here. So I suggest deleting this line. 
The minus sign here `-` means I suggest removing the line.

2022-01-24 15:27 UTC, myeung18 commented on controllers/reconcilers/cockroachdb_installation/cockroachdb_installation_reconciler.go
> +var _ reconcilers.PlatformReconciler = &Reconciler{}
ok,
Just my practice to do the type checking.

2022-01-25 19:52 UTC, xieshenzh requested changes

2022-01-25 19:52 UTC, xieshenzh commented on controllers/reconcilers/cockroachdb_installation/cockroachdb_installation_reconciler.go
> +var _ reconcilers.PlatformReconciler = (*Reconciler)(nil)
This line of code assigns `nil` to a blank identifier. 
Is there any reason why we want to merge it to the main branch?
If you just need to practice something, it is better to keep it in a branch of yours.

2022-01-25 20:19 UTC, myeung18 commented on controllers/reconcilers/cockroachdb_installation/cockroachdb_installation_reconciler.go
> +var _ reconcilers.PlatformReconciler = (*Reconciler)(nil)
again, it is a way of doing type checking. 
practice I mean coding standard.

2022-01-25 20:38 UTC, xieshenzh commented on controllers/reconcilers/cockroachdb_installation/cockroachdb_installation_reconciler.go
> +var _ reconcilers.PlatformReconciler = (*Reconciler)(nil)
The type is already checked at line 30, the return type of function `NewReconciler` is `reconcilers.PlatformReconciler` and the function returns an instance of `Reconciler`. If `Reconciler` doesn't implement `reconcilers.PlatformReconciler`, you will get an error at line 30.
Assigning to a blank identifier is normally used when [there are no static conversions that would cause the compiler to verify it automatically, which is a rare event](https://go.dev/doc/effective_go#:~:text=The%20appearance%20of,a%20rare%20event.). And it is not the case here.

2022-01-25 20:45 UTC, myeung18 commented on controllers/reconcilers/cockroachdb_installation/cockroachdb_installation_reconciler.go
> +var _ reconcilers.PlatformReconciler = (*Reconciler)(nil)
that makes sense.

2022-02-01 22:57 UTC, tchughesiv requested changes
please rebase

2022-02-03 15:53 UTC, redhatHameed commented
@tchughesiv @xieshenzh can we merge this? or there is anything remaining?

2022-02-03 15:53 UTC, redhatHameed approved these changes

2022-02-03 15:58 UTC, tchughesiv approved these changes

2022-02-03 15:58 UTC, tchughesiv commented on controllers/reconcilers/cockroachdb_installation/cockroachdb_installation_reconciler.go
> +}
it seems like these are all duplicate functions, for the most part, that should be consolidated to handle all 3 providers. that said, i think we can do that in a separate PR.

2022-02-03 16:04 UTC, redhatHameed commented on controllers/reconcilers/cockroachdb_installation/cockroachdb_installation_reconciler.go
> +}
Agree, we can add generic implementation for all providers. So less code implementation for future providers.

2022-02-03 16:07 UTC, xieshenzh commented
> @tchughesiv @xieshenzh can we merge this? or there is anything remaining?
> 
> @xieshenzh we need to push the image into repository ecosystem-appeng-> ccapi-k8s-operator-catalog

I have pushed the images.

2022-02-03 16:07 UTC, xieshenzh approved these changes

2022-02-03 16:08 UTC, tchughesiv reviewed
@redhatHameed @myeung18 do we not have any unit tests for the other providers?

2022-02-03 16:12 UTC, redhatHameed commented
> @redhatHameed @myeung18 do we not have any unit tests for the other providers?

Yes, we don't have a unit test for platform installation. With unit test installation never completed and always returning in progress we got timeout errors.

2022-02-03 16:41 UTC, merged

2022-02-10 00:03 UTC, bmozaffa commented
I must be forgetting something... but why is this a thing? Aren't we supporting dynamic addition of provider operators? Why not?